In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('kp_all_movies.csv')

In [3]:
movies.head()

,movie_id,name_rus,kp_rating,movie_duration,kp_rating_count,movie_year,imdb_rating,imdb_rating_count,genres,countries,budget,critics_rating,name_eng
0,10000,Иезавель,7.411,104,518.0,1938,7.6,8585.0,"[драма, мелодрама]",[США],$1 250 000,94.0,Jezebel
1,100049,47 ронинов,7.660,204,297.0,1962,7.8,1496.0,"[боевик, драма, история]",[Япония],NaN,NaN,Chûshingura
2,10005,Живем один раз,7.168,86,330.0,1937,7.4,3812.0,"[фильм-нуар, драма, криминал]",[США],$575 000,100.0,You Only Live Once
3,100053,Колдун 2,7.745,113,109.0,2003,6.5,393.0,"[фэнтези, боевик]",[Япония],NaN,NaN,Onmyoji 2
4,100096,"Ильза, тигрица из Сибири",4.286,85,151.0,1977,4.9,1211.0,[ужасы],[Канада],CAD 250 000,NaN,Ilsa the Tigress of Siberia

In [4]:
movies.shape

(36417, 13)

## Удалим тв-шоу, сериалы

In [5]:
drop_indexs = []
for ind, movie in enumerate(movies['name_rus']):
    if 'ТВ' in movie or 'сериал' in movie:
        drop_indexs.append(ind)
movies = movies.drop(drop_indexs, axis=0)

In [6]:
movies = movies.reset_index(drop=True)

In [7]:
movies.shape

(26559, 13)

## Составим множество жанров

In [10]:
size = len(movies)
dict_of_genres = {}
for ind, genre_str in enumerate(movies['genres']):
    if str(genre_str) != 'nan':

        genre_str_lst = genre_str[1:-1].split(', ') 
        for genre in genre_str_lst:
            dict_of_genres[genre] = dict_of_genres.get(genre, 0) + 1

In [11]:
set_of_genres = set(dict_of_genres)
set_of_genres -= set(['игра', 'игра', 'короткометражка', 'новости', 'реальное ТВ'])
set_of_genres

{'аниме',
 'биография',
 'боевик',
 'вестерн',
 'военный',
 'детектив',
 'детский',
 'для взрослых',
 'документальный',
 'драма',
 'история',
 'комедия',
 'концерт',
 'криминал',
 'мелодрама',
 'музыка',
 'мультфильм',
 'мюзикл',
 'приключения',
 'семейный',
 'спорт',
 'триллер',
 'ужасы',
 'фантастика',
 'фильм-нуар',
 'фэнтези'}

## Бинарно закодируем наличие жанра

In [12]:
size = len(movies)
for feat in set_of_genres:
    movies[feat] = np.zeros(size)
    for ind, genre_str in enumerate(movies['genres']):
        if str(genre_str) != 'nan':
            if feat in genre_str:
                movies.loc[ind,feat] = 1
movies = movies.drop('genres', axis=1)

In [15]:
movies.shape

(26559, 38)

## Составим множество стран

In [17]:
size = len(movies)
dict_of_countries = {}

for ind, country_str in enumerate(movies['countries']):
    if str(genre_str) != 'nan':
#         print(country_str)
        country_str_lst = country_str[1:-1].split(', ')   
        for country in country_str_lst:
            dict_of_countries[country] = dict_of_countries.get(country, 0) + 1      
dict_of_countries

{'США': 12354,
 'Япония': 1168,
 'Канада': 1220,
 'Франция': 3347,
 'Италия': 1435,
 'Великобритания': 2835,
 'Швейцария': 188,
 'Чехословакия': 64,
 'Нидерланды': 244,
 'Румыния': 88,
 'Германия (ФРГ)': 296,
 'ЮАР': 91,
 'Мексика': 143,
 'Германия': 1543,
 'Ливия': 3,
 'Ливан': 3,
 'Кувейт': 1,
 'Марокко': 16,
 'Индия': 663,
 'Греция': 42,
 'Австралия': 415,
 'Ирландия': 187,
 'Израиль': 75,
 'Бельгия': 346,
 'Испания': 696,
 'Китай': 286,
 'Гонконг': 437,
 'Чехия': 106,
 'Люксембург': 104,
 'Португалия': 54,
 'Сингапур': 28,
 'Австрия': 121,
 'Кипр': 1,
 'Дания': 258,
 'Эстония': 22,
 'Финляндия': 112,
 'Венгрия': 118,
 'Латвия': 19,
 'Литва': 24,
 'Мальта': 5,
 'Польша': 237,
 'Словакия': 15,
 'Словения': 11,
 'Швеция': 312,
 'Корея Южная': 514,
 'Россия': 1960,
 'Камерун': 4,
 'Норвегия': 171,
 'Таиланд': 91,
 'Бразилия': 84,
 'Тайвань': 75,
 'Аргентина': 119,
 'Аруба': 8,
 'Болгария': 51,
 'Ямайка': 3,
 'Югославия': 47,
 'Турция': 77,
 'Исландия': 56,
 'Босния-Герцеговина': 13,
 'Мали': 1,
 'Буркина-Фасо': 2,
 'Хорватия': 18,
 'Сербия и Черногория': 3,
 'Иран': 45,
 'Тунис': 12,
 'СССР': 1889,
 'Германия (ГДР)': 37,
 'Куба': 14,
 'Украина': 210,
 'Лихтенштейн': 9,
 'Пуэрто Рико': 7,
 'Югославия (ФР)': 8,
 'Сенегал': 4,
 'Перу': 14,
 'Сербия': 30,
 'Чили': 32,
 'Новая Зеландия': 83,
 'Казахстан': 65,
 'Филиппины': 12,
 'Алжир': 9,
 'Малайзия': 14,
 'Египет': 10,
 'Макао': 1,
 'Кыргызстан': 3,
 'Ботсвана': 3,
 'Македония': 9,
 'Беларусь': 63,
 'Остров Мэн': 4,
 'ОАЭ': 18,
 'Таджикистан': 4,
 'Грузия': 25,
 'Иордания': 4,
 'Колумбия': 15,
 'Армения': 33,
 'Вьетнам': 9,
 'Уругвай': 8,
 'Монголия': 6,
 'Корея Северная': 2,
 'Индонезия': 19,
 'Кения': 3,
 'Саудовская Аравия': 4,
 'Гана': 2,
 'Российская империя': 8,
 'Намибия': 2,
 'Бутан': 3,
 'Камбоджа': 3,
 'Гондурас': 1,
 'Доминикана': 2,
 'Азербайджан': 8,
 'Либерия': 1,
 '': 10,
 'Шри-Ланка': 3,
 'Сирия': 4,
 'Узбекистан': 6,
 'Гренландия': 1,
 'Венесуэла': 7,
 'Албания': 2,
 'Сальвадор': 1,
 'Танзания': 1,
 'Боливия': 2,
 'Афганистан': 4,
 'Папуа - Новая Гвинея': 1,
 'Оккупированная Палестинская территория': 1,
 'Багамы': 3,
 'Монако': 2,
 'Бахрейн': 1,
 'Руанда': 1,
 'Ангола': 1,
 'Непал': 1,
 'Чад': 1,
 'Молдова': 2,
 'Катар': 3,
 'Панама': 4,
 'Гаити': 3,
 'Замбия': 3,
 'Бангладеш': 3,
 'Реюньон': 1,
 'Ирак': 2,
 'Эквадор': 2,
 'Черногория': 2,
 'Лаос': 1,
 'Парагвай': 2,
 'Палестина': 2,
 'Коста-Рика': 1,
 'Мавритания': 1,
 'Конго': 1,
 'Уганда': 1}

In [19]:
europe_countries = set(['Лихтенштейн', 'Греция', 'Португалия', 'Мальта', 'Словакия', 'Черногория', 
                        'Словения', 'Хорватия', 'Швеция', 'Польша', 'Болгария', 'Босния-Герцеговина',
                       'Норвегия', 'Монако', 'Германия'])

pribaltyka = set(['Эстония', 'Латвия', 'Литва'])

USSR = set(['Грузия', 'Украина', 'Беларусь', 'Таджикистан', 'Армения', 'Азербайджан', 
            'Узбекистан', 'Россия', 'Казахстан', 'СССР'])

afrika = set(['Ливия', 'Ливан', 'Марокко', 'Камерун', 'Иран', 'Алжир', 'Египет', 
              'Саудовская Аравия','Уганда',  'Камбоджа'])

asia = set(['Сингапур', 'Таиланд', 'Япония', 'Китай'])

set_of_countries = set([country for country in dict_of_countries if dict_of_countries[country] > 500])
set_of_countries

{'Великобритания',
 'Германия',
 'Индия',
 'Испания',
 'Италия',
 'Канада',
 'Корея Южная',
 'Россия',
 'СССР',
 'США',
 'Франция',
 'Япония'}

## Бинарно закодируем основные страны

In [21]:
size = len(movies)

for feat in set_of_countries:
    movies[feat] = np.zeros(size)
    for ind, country_str in enumerate(movies['countries']):
        if str(country_str) != 'nan':
            if feat in country_str:
                movies.loc[ind,feat] = 1

## Бинарно закодируем группы стран

In [27]:
size = len(movies)
for country in ['Европа', 'Прибалтика', 'Наше', 'Африка', 'Азия']:
    movies[country] = np.zeros(size)

for ind, country_str in enumerate(movies['countries']):
    if str(country_str) != 'nan':
        country_set_i = set(country_str[1:-1].split(', '))
        
        if len(country_set_i & europe_countries) != 0:
            movies.loc[ind, 'Европа'] = 1
            
        if len(country_set_i & pribaltyka) != 0:
            movies.loc[ind, 'Прибалтика'] = 1
            
        if len(country_set_i & USSR) != 0:
            movies.loc[ind, 'Наше'] = 1
            
        if len(country_set_i & afrika) != 0:
            movies.loc[ind, 'Африка'] = 1
            
        if len(country_set_i & asia) != 0:
            movies.loc[ind, 'Азия'] = 1

In [33]:
movies.to_csv('preproc_movies.csv')

## Выделяем киновселенные, трилогии ..

# Работаем с другим датасетами

In [38]:
disney = pd.read_csv('DisneyMoviesDataset.csv',index_col=0 )
disney.head()

,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),Release date (datetime),...,Box office,Story by,Narrated by,Cinematography,Edited by,Screenplay by,Production companies,Adaptation by,Traditional,Simplified
0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,1937-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,1937-12-21,...,$418 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,1940-02-07,...,$164 million,"['Ted Sears', 'Otto Englander', 'Webb Smith', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,1940-11-13,...,$76.4–$83.3 million,"['Joe Grant', 'Dick Huemer']",Deems Taylor,James Wong Howe,NaN,NaN,NaN,NaN,NaN,NaN
4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,1941-06-20,...,"$960,000 (worldwide rentals)",NaN,NaN,Bert Giennon,Paul Weatherwax,NaN,NaN,NaN,NaN,NaN

In [39]:
imdb_movies = pd.read_csv('IMDb movies.csv')
imdb_movies.head()

/home/mike/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [40]:
imdb_names = pd.read_csv('IMDb names.csv')
imdb_names.head()

,imdb_name_id,name,birth_name,height,bio,birth_details,date_of_birth,place_of_birth,death_details,date_of_death,place_of_death,reason_of_death,spouses_string,spouses,divorces,spouses_with_children,children
0,nm0000001,Fred Astaire,Frederic Austerlitz Jr.,177.0,"Fred Astaire was born in Omaha, Nebraska, to J...","May 10, 1899 in Omaha, Nebraska, USA",1899-05-10,"Omaha, Nebraska, USA","June 22, 1987 in Los Angeles, California, USA ...",1987-06-22,"Los Angeles, California, USA",pneumonia,Robyn Smith (27 June 1980 - 22 June 1987) (hi...,2,0,1,2
1,nm0000002,Lauren Bacall,Betty Joan Perske,174.0,Lauren Bacall was born Betty Joan Perske on Se...,"September 16, 1924 in The Bronx, New York City...",1924-09-16,"The Bronx, New York City, New York, USA","August 12, 2014 in New York City, New York, US...",2014-08-12,"New York City, New York, USA",stroke,Jason Robards (4 July 1961 - 10 September 196...,2,1,2,3
2,nm0000003,Brigitte Bardot,Brigitte Bardot,166.0,"Brigitte Bardot was born on September 28, 1934...","September 28, 1934 in Paris, France",1934-09-28,"Paris, France",NaN,NaN,NaN,NaN,Bernard d'Ormale (16 August 1992 - present)\n...,4,3,1,1
3,nm0000004,John Belushi,John Adam Belushi,170.0,"John Belushi was born in Chicago, Illinois, US...","January 24, 1949 in Chicago, Illinois, USA",1949-01-24,"Chicago, Illinois, USA","March 5, 1982 in Hollywood, Los Angeles, Calif...",1982-03-05,"Hollywood, Los Angeles, California, USA",acute cocaine and heroin intoxication,Judith Belushi-Pisano (31 December 1976 - 5 M...,1,0,0,0
4,nm0000005,Ingmar Bergman,Ernst Ingmar Bergman,179.0,"Ernst Ingmar Bergman was born July 14, 1918, t...","July 14, 1918 in Uppsala, Uppsala län, Sweden",1918-07-14,"Uppsala, Uppsala län, Sweden","July 30, 2007 in Fårö, Gotlands län, Sweden (...",2007-07-30,"Fårö, Gotlands län, Sweden",natural causes,Ingrid Bergman (11 November 1971 - 20 May 199...,5,4,5,8

In [42]:
imdb_ratings = pd.read_csv('IMDb ratings.csv')
imdb_ratings.head()

,imdb_title_id,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,...,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0
1,tt0000574,6.1,589,6.3,6.0,57,18,58,137,139,...,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0
2,tt0001892,5.8,188,6.0,6.0,6,6,17,44,52,...,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0
3,tt0002101,5.2,446,5.3,5.0,15,8,16,62,98,...,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0
4,tt0002130,7.0,2237,6.9,7.0,210,225,436,641,344,...,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0

## Востанавливаем пропуски бюджета

## Метка дисней

## Популярные актеры

In [76]:
for budget in movies['budget']:
    print(type(budget), budget)

<class 'str'> $1 250 000
<class 'float'> nan
<class 'str'> $575 000
<class 'float'> nan
<class 'str'> CAD 250 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 140 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 910 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $5 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $52 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $783 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $300 000 000
<class 'str'> $25 000 000
<class 'str'> $30 000 000
<class 'str'> $39 000 000
<class 'str'> $40 000 000
<class 'str'> $21 000 000
<class 'str'> $45 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $3 700 000
<class 'str'> INR 700 000 000
<class 'float'> nan
<class 'str'> $130 000 000
<class 'str'> $30 000 000
<class 'str'> $40 000 000
<class 'str'> $500 000
<class 'str'> $150 000 000
<class 'str'> $16 500 000
<class 'str'> $1 234 567
<class 'str'> $10 000
<class 'str'> $52 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $10 000 000
<class 'str'> €2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $16 500 000
<class 'str'> $2 000 000
<class 'str'> $61 000 000
<class 'str'> $34 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $60 000 000
<class 'str'> $7 000 000
<class 'str'> $50 000 000
<class 'str'> $10 000 000
<class 'str'> $60 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $150 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> INR 350 000 000
<class 'str'> INR 100 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> ¥2 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €25 320 000
<class 'str'> $2 459 000
<class 'str'> €35 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 800 000
<class 'str'> $460 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> €14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $2 200 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> KRW 4 200 000 000
<class 'str'> $18 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $105 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $160 000 000
<class 'str'> FRF 25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $936 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000
<class 'str'> $12 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 20 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $5 000 000
<class 'str'> $14 100 000
<class 'str'> $6 000 000
<class 'str'> $6 200 000
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $42 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $34 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> € 33 000 000
<class 'str'> $225 000
<class 'str'> £1 278 000
<class 'str'> $950 000
<class 'float'> nan
<class 'str'> $3 600 000
<class 'float'> nan
<class 'str'> €20 000 000
<class 'str'> $3 200 000
<class 'str'> €200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 6 000 000
<class 'str'> $65 000 000
<class 'str'> $20 500 000
<class 'float'> nan
<class 'str'> £3 500 000
<class 'str'> $3 200 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> €4 750 000
<class 'float'> nan
<class 'str'> CNY 1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CNY 10 000 000
<class 'str'> $5 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $67 000 000
<class 'str'> $23 000 000
<class 'str'> $17 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $200 000
<class 'str'> $1 000 000
<class 'str'> $3 000 000
<class 'str'> $28 000 000
<class 'str'> INR 32 636 250
<class 'str'> $15 000 000
<class 'str'> $19 000 000
<class 'str'> $130 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $45 000 000
<class 'str'> $25 000 000
<class 'str'> $19 000 000
<class 'str'> $5 000 000
<class 'str'> $175 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 601 792
<class 'str'> $210 000
<class 'float'> nan
<class 'str'> INR 100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 160 000
<class 'str'> $2 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 645 000
<class 'str'> $1 486 000
<class 'float'> nan
<class 'str'> $305 177
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $558 000
<class 'str'> $70 000 000
<class 'str'> SEK 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 1 700 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €22 000 000
<class 'str'> $17 000 000
<class 'str'> €7 600 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $150 000 000
<class 'str'> $4 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'str'> £25 000 000
<class 'str'> $70 000 000
<class 'str'> $60 795 000
<class 'str'> $2 000 000
<class 'str'> $19 000 000
<class 'str'> $85 000 000
<class 'str'> €24 400 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $20 000 000
<class 'str'> $15 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $3 000 000
<class 'str'> $1 100 000
<class 'str'> $500 000
<class 'str'> $39 000 000
<class 'str'> $14 000 000
<class 'str'> $22 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $35 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> FIM 4 773 394
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $15 000 000
<class 'str'> $38 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> €2 870 000
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥1 500 000 000
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'str'> CAD 8 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $73 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $1 300 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'str'> CAD 100 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $8 000 000
<class 'str'> $20 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £3 000 000
<class 'str'> £5 000 000
<class 'str'> $65 000
<class 'str'> $24 500
<class 'float'> nan
<class 'float'> nan
<class 'str'> $34 000 000
<class 'str'> $1 516 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 200 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 15 155 100
<class 'str'> NOK 4 000 000
<class 'float'> nan
<class 'str'> $1 558 000
<class 'float'> nan
<class 'str'> €2 292 046
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $6 900 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $1 100 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $725 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> €10 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> €10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $90 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> CAD 5 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $1 300 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $10 000 000
<class 'str'> ¥500 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $250 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $33 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $40 000 000
<class 'str'> MXN 18 000 000
<class 'float'> nan
<class 'str'> £2 900 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $34 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> €1 400 000
<class 'str'> $18 000 000
<class 'str'> $60 000 000
<class 'str'> $33 000 000
<class 'str'> $24 000 000
<class 'str'> $6 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'str'> $28 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> AUD 10 000 000
<class 'str'> $30 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $185 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 238 813
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $5 019 770
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 805 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $220 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $2 750 000
<class 'str'> $3 705 000
<class 'str'> $3 000 000
<class 'str'> $1 800 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $855 000
<class 'str'> $928 000
<class 'float'> nan
<class 'str'> $1 243 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> €37 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 200 000
<class 'str'> DEM 3 000 000
<class 'str'> $1 705 000
<class 'str'> $5 400 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $2 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> €22 100 000
<class 'str'> $3 800 000
<class 'str'> DEM 42 000 000
<class 'str'> DEM 20 000 000
<class 'str'> PLN 6 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'str'> $40 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $5 000 000
<class 'str'> $12 000 000
<class 'str'> $13 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> €1 400 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> $10 500 000
<class 'str'> $25 000 000
<class 'str'> $50 000 000
<class 'str'> $27 000 000
<class 'float'> nan
<class 'str'> $110 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 21 500 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $88 000 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 3 465 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $51 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $19 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $10 000 000
<class 'str'> $2 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $57 000 000
<class 'str'> $48 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $1 800 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $23 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $7 623 000
<class 'float'> nan
<class 'str'> £280 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $360 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $11 700 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> CAD 2 500 000
<class 'str'> $8 000 000
<class 'str'> $38 000 000
<class 'str'> $90 000 000
<class 'str'> $80 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 300 000
<class 'float'> nan
<class 'str'> HUF 80 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $991 000
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 300 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $5 000 000
<class 'str'> $4 353 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $1 000 000
<class 'str'> $1 640 000
<class 'str'> $100 000
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $190 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 685 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 853 463
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $171 200
<class 'float'> nan
<class 'str'> $257 502
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $980 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 800 000
<class 'str'> $11 000 000
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $80 000 000
<class 'str'> NLG 1 200 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $6 580 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $35 200 000
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 062 256
<class 'str'> $4 474 000
<class 'str'> $3 700 000
<class 'float'> nan
<class 'str'> $3 240 816
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 680 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $40 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $1 300 000
<class 'str'> $2 235 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 370 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $251 289
<class 'float'> nan
<class 'str'> $4 653 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $40 000 000
<class 'str'> $14 000 000
<class 'str'> $88 000 000
<class 'str'> $20 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> FIM 23 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $12 000 000
<class 'str'> $19 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $3 716 946
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $4 600 000
<class 'str'> $4 520 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'str'> $100 000
<class 'str'> $1 240 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $6 000 000
<class 'str'> $7 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $1 125 000
<class 'str'> $20 000 000
<class 'str'> $7 400 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'str'> $20 000 000
<class 'str'> $1 214 899
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $1 600 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $2 503 654
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 274 620 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $10 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $3 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000
<class 'str'> $60 000
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $98 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> CAD 3 000 000
<class 'str'> $3 800 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $6 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 700 000
<class 'str'> $2 650 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $70 000
<class 'float'> nan
<class 'str'> $1 253 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €27 440 000
<class 'str'> €15 300 000
<class 'str'> FRF 140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 50 000 000
<class 'float'> nan
<class 'str'> FRF 50 000 000
<class 'float'> nan
<class 'str'> FRF 17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $86 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> €22 900 000
<class 'str'> €7 800 000
<class 'float'> nan
<class 'str'> €21 740 000
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> €5 320 000
<class 'str'> $1 300 000
<class 'str'> €5 350 000
<class 'str'> €14 090 000
<class 'str'> €4 520 000
<class 'str'> €7 500 000
<class 'str'> €6 950 000
<class 'str'> FRF 4 000 000
<class 'str'> FRF 77 000 000
<class 'str'> FRF 53 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $740 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $1 500 000
<class 'str'> $1 125 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 210 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $187 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 200 000
<class 'str'> DEM 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 250 000
<class 'str'> $3 352 254
<class 'str'> $3 200 000
<class 'str'> $7 573 797
<class 'str'> $2 500 000
<class 'str'> $240 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $25 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $6 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $12 164 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $4 000 000
<class 'str'> €5 310 000
<class 'str'> $130 000
<class 'float'> nan
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $1 700 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 200 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> $5 740 000
<class 'str'> AUD 10 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $11 500 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $20 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> DEM 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $850 000
<class 'float'> nan
<class 'str'> $70 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $15 000 000
<class 'str'> AUD 12 000 000
<class 'float'> nan
<class 'str'> AUD 2 600 000
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $435 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $260 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $408 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $424 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> €14 500 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $170 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $45 000 000
<class 'str'> $80 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $26 000 000
<class 'str'> $1 614 000
<class 'float'> nan
<class 'str'> $578 000
<class 'str'> $1 300 000
<class 'str'> $923 055
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 900 000
<class 'str'> $15 000 000
<class 'str'> $100 000
<class 'str'> $20 000 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000
<class 'float'> nan
<class 'str'> $100 000
<class 'str'> $1 300 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $62 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $40 000 000
<class 'str'> $120 000 000
<class 'str'> $40 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $46 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'str'> $76 000 000
<class 'str'> $10 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $30 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $85 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $83 532
<class 'float'> nan
<class 'str'> £250 000
<class 'str'> $1 500 000
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $115 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $1 000 000
<class 'str'> DEM 1 100 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $54 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €15 000 000
<class 'str'> $15 000 000
<class 'str'> $200 000 000
<class 'str'> £2 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 600 000
<class 'str'> $140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $15 000 000
<class 'str'> $65 000 000
<class 'str'> $6 600 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $1 100 000
<class 'str'> $15 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $3 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> PLN 3 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 500 000
<class 'str'> €1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $520 000
<class 'float'> nan
<class 'str'> £9 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $1 271 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 574 422
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $10 000 000
<class 'str'> $13 000 000
<class 'str'> $2 900 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $3 200 000
<class 'float'> nan
<class 'str'> $1 818 688
<class 'float'> nan
<class 'str'> £610 000
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $650 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $7 300 000
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $800 000
<class 'str'> $3 000 000
<class 'str'> $80 000 000
<class 'str'> $15 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $430 290
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $88 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 166 000
<class 'float'> nan
<class 'str'> £60 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $12 000 000
<class 'str'> $11 000 000
<class 'str'> AUD 3 900 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> ESP 20
<class 'float'> nan
<class 'str'> £200 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 39 000 000
<class 'str'> $8 500 000
<class 'str'> $30 000 000
<class 'str'> $1 831 927
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $110 000 000
<class 'str'> $3 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $850 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $5 000 000
<class 'str'> $8 000 000
<class 'str'> $1 500 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> FFR 65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 700 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $47 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $11 500 000
<class 'str'> £3 000 000
<class 'str'> £5 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> £1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $8 000 000
<class 'str'> $15 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> DKK 6 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $31 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $1 200 000
<class 'str'> $6 200 000
<class 'str'> $4 000 000
<class 'str'> CAD 4 500 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $54 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $700 000
<class 'str'> $500 000
<class 'str'> $450 000
<class 'str'> $930 000
<class 'str'> $18 000 000
<class 'str'> $20 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $450 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> CAD 7 716 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $92 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $5 000 000
<class 'str'> $60 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $8 500 000
<class 'str'> $4 500 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 240 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 60 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $275 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $1 570 000
<class 'str'> $7 200 000
<class 'float'> nan
<class 'str'> $1 455 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 000 000
<class 'str'> $24 000
<class 'str'> $9 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $1 800 000
<class 'str'> $5 000 000
<class 'str'> $8 500 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> $1 000 000
<class 'str'> $40 000 000
<class 'str'> $12 000 000
<class 'str'> $33 000 000
<class 'str'> $42 000 000
<class 'str'> $90 000 000
<class 'str'> $24 000 000
<class 'str'> $30 000 000
<class 'str'> $2 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $8 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $2 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €1 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $650 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ESP 1 200 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $134 000
<class 'str'> $130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $30 000 000
<class 'str'> $110 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $25 000 000
<class 'str'> $2 926 000
<class 'str'> $110 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $1 000 000
<class 'str'> $11 000 000
<class 'str'> $10 000 000
<class 'str'> $4 000 000
<class 'str'> $44 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $5 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $67 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $120 000 000
<class 'str'> $9 000 000
<class 'str'> $40 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan

<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $10 000 000
<class 'str'> $120 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £35 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 840 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £300 000
<class 'str'> $175 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000
<class 'str'> $100 000
<class 'str'> $200 000
<class 'str'> $200 000
<class 'str'> $225 000
<class 'str'> $250 000
<class 'str'> $200 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> £500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $275 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $3 500 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 530 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $6 500 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $9 000 000
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $79 000 000
<class 'str'> €14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $50 000 000
<class 'str'> $90 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $6 000 000
<class 'str'> $75 000 000
<class 'str'> $2 000 000
<class 'str'> $21 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $1 200 000
<class 'str'> $30 000 000
<class 'str'> $15 500 000
<class 'str'> $24 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> €3 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $20 000 000
<class 'str'> €78 000 000
<class 'float'> nan
<class 'str'> $60 000
<class 'str'> £2 600 000
<class 'str'> $75 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $36 000 000
<class 'str'> $30 000 000
<class 'str'> $37 000 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $150 000 000
<class 'str'> $18 000 000
<class 'str'> $28 000 000
<class 'str'> $130 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $100 000 000
<class 'str'> $25 000 000
<class 'str'> £4 000 000
<class 'str'> $130 000 000
<class 'str'> $11 000 000
<class 'str'> $2 400 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $25 000 000
<class 'str'> $3 500 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $57 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $40 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $140 000 000
<class 'str'> $35 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> £1 500 000
<class 'str'> $2 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> €462 000
<class 'str'> £2 500 000
<class 'str'> €1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 8 000 000
<class 'float'> nan
<class 'str'> $71 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> £1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $25 000 000
<class 'str'> $16 000 000
<class 'str'> $2 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $58 000 000
<class 'str'> $5 000 000
<class 'str'> $1 000 000
<class 'str'> €5 340 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $25 000 000
<class 'str'> €7 100 000
<class 'str'> $30 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $16 800 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> €1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 200 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $15 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $100 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> £1 500 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 500 000
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $180 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> €8 900 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000
<class 'str'> €1 380 000
<class 'float'> nan
<class 'str'> $85 000 000
<class 'float'> nan
<class 'str'> INR 400 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $17 500 000
<class 'str'> $70 000 000
<class 'str'> $3 400 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $16 000 000
<class 'str'> $130 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $135 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 200 000
<class 'str'> $24 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $3 520 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $615 065
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $807 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $6 500 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 1 100 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $450 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $120 000
<class 'str'> $28 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $230 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $4 000 000
<class 'str'> $65 000 000
<class 'str'> $6 000 000
<class 'str'> $17 000 000
<class 'str'> $947 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $125 000 000
<class 'str'> $14 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $640 000
<class 'str'> $18 000 000
<class 'str'> $240 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 365 000
<class 'float'> nan
<class 'str'> £1 000 000
<class 'str'> $800 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 058 000
<class 'str'> $1 152 000
<class 'str'> $1 279 142
<class 'str'> $3 000 000
<class 'str'> $652 675
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 200 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $39 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> THB 60 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 164 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $1 688 000
<class 'str'> $3 900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 800 000
<class 'str'> $2 000 000
<class 'str'> CAD 2 000 000
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $15 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 80 000
<class 'str'> CAD 1 500 000
<class 'str'> CAD 350 000
<class 'str'> CAD 8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $3 500 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $3 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $650 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $351 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 500 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $111 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 71 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 4 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 76 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 210 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £90 000
<class 'str'> £300 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $7 000 000
<class 'str'> $1 200 000
<class 'str'> $35 000 000
<class 'str'> DKK 8 600 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $12 000 000
<class 'str'> $6 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $1 300 000
<class 'str'> $23 000 000
<class 'str'> $28 000 000
<class 'str'> €2 600 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> CAD 3 500 000

<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 618 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $300 000
<class 'float'> nan
<class 'str'> $65 000
<class 'str'> $25 000
<class 'str'> $10 000
<class 'str'> $2 100
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $450 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $5 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £250 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 500 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> SEK 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> CAD 6 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 200 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 16 500 000 руб.
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $3 000 000
<class 'str'> $700 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> DEM 3 500 000
<class 'str'> DEM 10 500 000
<class 'str'> DEM 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $450 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $14 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 1 000 000
<class 'str'> $1 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $700 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> AUD 800 000
<class 'str'> $9 500 000
<class 'str'> $9 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'str'> $3 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €11 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $25 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $145 786
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $2 000 000
<class 'str'> CHF 5 000 000
<class 'str'> CAD 5 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $23 000
<class 'str'> $5 000 000
<class 'str'> $11 500 000
<class 'str'> $2 000 000
<class 'str'> $9 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $740 000
<class 'float'> nan
<class 'str'> $10 200 000
<class 'float'> nan
<class 'str'> CAD 1 500 000
<class 'float'> nan
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €546 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 800 000
<class 'str'> $25 000 000
<class 'str'> $26 000 000
<class 'str'> $12 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $35 000 000
<class 'str'> AUD 2 200 000
<class 'float'> nan
<class 'str'> $47 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $4 500 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> ISK 130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 200 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $500 000
<class 'str'> $69 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $62 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $6 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $23 000 000
<class 'str'> $30 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $120 000 000
<class 'str'> $1 000 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 2 000 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €11 590 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> ZAR 34 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $54 000 000
<class 'str'> $8 000 000
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> BRL 300 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 200 000
<class 'str'> $140 000
<class 'str'> $17 080 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $15 000 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> CAD 4 100 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $4 000 000
<class 'str'> $2 300 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $45 000 000
<class 'str'> $11 000 000
<class 'str'> $70 000 000
<class 'str'> $15 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥800 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> CAD 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $225 000 000
<class 'str'> $17 000 000
<class 'str'> €1 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $49 000 000
<class 'str'> $16 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $10 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $37 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥14 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $2 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> HKD 200 000 000
<class 'str'> HKD 30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> HKD 2 000 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 115 000 000
<class 'float'> nan
<class 'str'> HKD 64 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $850 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 100 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $6 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> CAD 1 200 000
<class 'str'> CAD 179 000
<class 'str'> $20 000
<class 'str'> $3 500
<class 'str'> CAD 5 400 000
<class 'float'> nan
<class 'str'> CAD 5 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $52 000 000
<class 'str'> $2 200 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 585 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $220 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 631 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> AUD 1 800 000
<class 'str'> CAD 1 600 000
<class 'float'> nan
<class 'str'> $53 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $2 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $237 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $4 000 000
<class 'str'> $19 000 000
<class 'str'> € 28 000 000
<class 'str'> $80 000 000
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $165 000 000
<class 'str'> € 12 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $12 000 000
<class 'str'> $60 000 000
<class 'str'> $10 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $45 000 000
<class 'str'> £5 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $10 000
<class 'float'> nan
<class 'str'> €11 700 000
<class 'str'> $2 000 000
<class 'str'> $5 250 000
<class 'str'> $120 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $850 000
<class 'str'> CAD 4 000 000
<class 'str'> $16 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> PLN 4 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $12 000 000
<class 'str'> $30 000 000
<class 'str'> €4 200 000
<class 'str'> $150 000 000
<class 'str'> NZD 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> £1 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> THB 300 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> €500 000
<class 'float'> nan
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $12 000 000
<class 'str'> $750 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $5 000 000
<class 'str'> €600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> £500 000
<class 'str'> NOK 22 000 000
<class 'str'> $15 000 000
<class 'str'> NOK 14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 35 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $130 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $5 000 000
<class 'str'> $1 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 500 000
<class 'str'> €2 000 000
<class 'float'> nan
<class 'str'> €3 500 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> €1 500 000
<class 'float'> nan
<class 'str'> $54 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $160 000 000
<class 'str'> $3 800 000
<class 'str'> $9 000 000
<class 'str'> $125 000 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> HUF 600 000 000
<class 'str'> $4 000 000
<class 'str'> $15 000 000
<class 'str'> ¥10 000 000
<class 'float'> nan
<class 'str'> £4 000 000
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'str'> £2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> €2 100 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $30 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥3 400 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $4 500 000
<class 'str'> $14 000 000
<class 'str'> €24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $5 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000 000
<class 'str'> NOK 60 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $47 000 000
<class 'str'> $2 500 000
<class 'str'> €30 400 000
<class 'str'> $40 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $16 500 000
<class 'str'> €18 000 000
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €4 500 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $60 000 000
<class 'str'> $190 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $2 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 400 000
<class 'str'> €3 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 460 000
<class 'str'> $10 000 000
<class 'str'> $18 000 000
<class 'str'> €4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'str'> CAD 11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $546 883
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> €2 457 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> £11 000 000
<class 'float'> nan
<class 'str'> € 12 500 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> € 9 780 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> €4 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 20 000 000
<class 'float'> nan
<class 'str'> €8 400 000
<class 'str'> $5 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $1 000 000
<class 'str'> $15 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $220 000 000
<class 'str'> AUD 8 500 000
<class 'str'> €1 000 000
<class 'str'> €600 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $225 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $326 000
<class 'str'> £1 200 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> INR 150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> €7 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $6 500 000
<class 'str'> €6 000 000
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> €1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $90 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> CZK 84 450 000
<class 'str'> $4 700 000
<class 'float'> nan
<class 'str'> €3 000 000
<class 'str'> $8 000 000
<class 'str'> €1 500 000
<class 'str'> €5 200 000
<class 'float'> nan
<class 'str'> INR 220 000 000
<class 'float'> nan
<class 'str'> €5 200 000
<class 'str'> $500 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $1 000 000
<class 'str'> €2 600 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $703 000
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $6 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 500 000
<class 'str'> €1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 750 000
<class 'float'> nan
<class 'str'> €25 000 000
<class 'str'> £4 000 000
<class 'str'> €10 000 000
<class 'str'> $2 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 200 000
<class 'float'> nan
<class 'str'> NOK 18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $610 000
<class 'str'> $433 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 1 300 000 руб.
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥1 000 000 000
<class 'str'> $4 000 000
<class 'str'> BRL 3 000 000
<class 'float'> nan
<class 'str'> €980 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $2 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 5 000 000
<class 'float'> nan
<class 'str'> BRL 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'str'> €20 000
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $38 000 000
<class 'str'> $55 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 590 920
<class 'float'> nan
<class 'str'> $29 000 000
<class 'str'> £500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> PLN 15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'str'> $125 000
<class 'str'> $4 500 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> €350 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $2 700 000
<class 'str'> £1 000 000
<class 'str'> $1 500 000
<class 'str'> $2 000 000
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $120 000 000
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $35 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'str'> $165 000 000
<class 'str'> $4 500 000
<class 'str'> $2 500 000
<class 'str'> $2 400 000
<class 'str'> $20 000 000
<class 'str'> $3 800 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 800 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $50 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $6 500 000
<class 'str'> $35 000 000
<class 'str'> $1 900 000
<class 'float'> nan
<class 'str'> £4 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 11 000 000
<class 'str'> €21 166 000
<class 'str'> $12 000 000
<class 'str'> $25 000 000
<class 'str'> $5 000 000
<class 'str'> €5 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> €24 500 000
<class 'str'> $10 000 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $8 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 47 000 000
<class 'str'> $8 000 000
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 400 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $12 000 000
<class 'str'> $35 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 500 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $15 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $1 210 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 250 000
<class 'float'> nan
<class 'str'> $2 592 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> KRW 370 000 000
<class 'str'> €4 300 000
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> $65 000 000
<class 'str'> $217 000
<class 'float'> nan
<class 'str'> $1 600 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> £500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $25 000 000
<class 'str'> ISK 180 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $4 600 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $4 200 000
<class 'str'> $36 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $3 768 785
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €24 000 000
<class 'float'> nan
<class 'str'> $5 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $64 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $170 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'str'> CAD 1 500 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $2 000 000
<class 'float'> nan

<class 'float'> nan
<class 'str'> DKK 45 000 000
<class 'str'> $145 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> £150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $14 500 000
<class 'str'> $6 000 000
<class 'str'> $12 000 000
<class 'str'> $4 500 000
<class 'str'> SEK 210 000 000
<class 'str'> CNY 10 000 000
<class 'str'> $75 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $17 500 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $8 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $92 000 000
<class 'str'> $230 000 000
<class 'str'> $15 500 000
<class 'str'> €65 000 000
<class 'str'> €65 000 000
<class 'float'> nan
<class 'str'> € 10 000 000
<class 'str'> $5 000 000
<class 'str'> €13 000 000
<class 'str'> $50 000 000
<class 'str'> $500 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> €6 000 000
<class 'str'> €2 287 772
<class 'str'> €8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $400 000
<class 'str'> €1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $180 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $180 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> €11 000 000
<class 'str'> $8 500 000
<class 'str'> $3 700 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 500 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $3 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $1 950 000
<class 'str'> $25 000 000
<class 'str'> $6 000 000
<class 'str'> $27 000 000
<class 'str'> $6 000 000
<class 'str'> $48 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $10 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> €4 500 000
<class 'str'> $8 000 000
<class 'str'> $7 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €25 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> €4 773 906
<class 'str'> $8 000 000
<class 'str'> $105 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> €20 000 000
<class 'str'> $40 000 000
<class 'str'> $10 000 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $30 000 000
<class 'str'> £1 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 000 000
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $60 000 000
<class 'str'> $13 500 000
<class 'str'> $55 000 000
<class 'str'> $2 500 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $165 000 000
<class 'str'> $175 000 000
<class 'str'> $85 000 000
<class 'str'> $62 000 000
<class 'str'> $80 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $2 550 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 700 000
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> THB 100 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $6 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 247 000
<class 'str'> $2 500 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 269 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 500 000
<class 'float'> nan
<class 'str'> £500 000
<class 'str'> $25 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> CAD 2 000 000
<class 'str'> $17 000 000
<class 'str'> $1 500 000
<class 'str'> $16 000 000
<class 'str'> $4 000 000
<class 'str'> $10 000 000
<class 'str'> $3 400 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> €1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $155 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> £900 000
<class 'str'> $39 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $24 000 000
<class 'str'> CAD 1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $6 000 000
<class 'str'> $5 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 600 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $40 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 440 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $15 000 000
<class 'str'> £92 000
<class 'str'> £45 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $9 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $22 000 000
<class 'str'> $200 000 000
<class 'str'> $29 000 000
<class 'str'> $1 000 000
<class 'str'> $100 000
<class 'str'> $130 000
<class 'str'> $31 190 000
<class 'str'> $50 000 000

<class 'str'> $50 000 000
<class 'str'> $120 000 000
<class 'str'> $1 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $650 000
<class 'str'> $1 000 000
<class 'str'> $16 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $75 000
<class 'str'> $130 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $130 000 000
<class 'str'> $60 000 000
<class 'str'> $2 800 000
<class 'str'> $70 000 000
<class 'str'> $2 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $140 000 000
<class 'str'> $2 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 500 000
<class 'str'> $14 000 000
<class 'str'> $35 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'str'> $520 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 250 000
<class 'float'> nan
<class 'str'> $5 400 000
<class 'str'> $87 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 620 000
<class 'float'> nan
<class 'str'> $3 200 000
<class 'float'> nan
<class 'str'> $110 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $93 000 000
<class 'float'> nan
<class 'str'> $68 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 686 000
<class 'str'> $2 500 000
<class 'str'> $75 000 000
<class 'str'> $60 000 000
<class 'str'> $60 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> CAD 1 400 000
<class 'str'> $150 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000
<class 'str'> $85 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $63 000 000
<class 'str'> $48 000 000
<class 'float'> nan
<class 'str'> $5 100 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $5 000 000
<class 'str'> $5 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 290 000
<class 'float'> nan
<class 'str'> $850 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $1 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $30 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $12 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $75 000
<class 'float'> nan
<class 'str'> $65 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> €400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> 10 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> $245 000
<class 'str'> $172 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> £1 500 000
<class 'str'> $5 000 000
<class 'str'> CAD 3 500 000
<class 'str'> $25 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 300 000
<class 'str'> $18 000 000
<class 'str'> $50 000 000
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $2 000 000
<class 'str'> € 10 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $8 500 000
<class 'str'> $37 000 000
<class 'str'> $15 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> INR 1 150 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> €11 000 000
<class 'str'> $4 000 000
<class 'str'> $20 000 000
<class 'str'> $7 000 000
<class 'str'> $22 000 000
<class 'str'> $52 000 000
<class 'float'> nan
<class 'str'> €35 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $450 000
<class 'str'> $4 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $94 000 000
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $1 800 000
<class 'str'> $2 500 000
<class 'str'> €4 400 000
<class 'str'> £3 500 159
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $52 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 21 277 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $20 000 000
<class 'str'> $1 005 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 4 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 680 000
<class 'str'> DEM 500 000
<class 'str'> DEM 850 000
<class 'float'> nan
<class 'str'> DEM 620 000
<class 'str'> DEM 12 000
<class 'str'> DKK 6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $180 000
<class 'str'> $60 000 000
<class 'str'> $3 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> DEM 12 000 000
<class 'float'> nan
<class 'str'> €5 700 000
<class 'float'> nan
<class 'str'> $125 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 6 000 000
<class 'str'> $1 000 000
<class 'str'> $5 000 000
<class 'str'> $6 000 000
<class 'str'> $2 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $239 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'str'> $60 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> €4 000 000
<class 'str'> €2 500 000
<class 'str'> €15 000
<class 'str'> $9 000 000
<class 'str'> $4 500 000
<class 'str'> AUD 15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €250 000
<class 'str'> $35 000 000
<class 'str'> THB 119 000 000
<class 'str'> $10 000 000
<class 'str'> FRF 30 000 000
<class 'float'> nan
<class 'str'> NOK 50 000 000
<class 'str'> $6 000 000
<class 'str'> $1 000 000
<class 'str'> $60 000 000
<class 'str'> $55 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $340 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €590 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $3 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> NLG 800 000
<class 'str'> NLG 800 000
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $12 500 000
<class 'str'> $4 000 000
<class 'str'> £90 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> CAD 15 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> € 100 000
<class 'str'> $30 000 000
<class 'str'> BRL 12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> £200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> CAD 4 500 000
<class 'str'> $1 500 000
<class 'str'> $218 869
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $115 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $95 745
<class 'str'> $20 000 000
<class 'str'> $40 000 000
<class 'str'> $7 000 000
<class 'str'> $1 500
<class 'str'> $196 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $130 000 000
<class 'str'> $10 000 000
<class 'str'> INR 100 000 000
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'str'> £3 500 000
<class 'float'> nan
<class 'str'> $45 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $25 000 000
<class 'str'> $60 000
<class 'str'> $20 000
<class 'str'> £1 100 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'str'> $76 000 000
<class 'str'> $15 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000
<class 'str'> CAD 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 4 000 000
<class 'float'> nan
<class 'str'> DEM 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $52 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $90 000 000
<class 'str'> €1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £180 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> €1 350 000
<class 'float'> nan
<class 'str'> NLG 5 000 000
<class 'str'> $175 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> LVL 2 197 496
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'str'> $5 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $3 750 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $45 000 000
<class 'str'> FRF 25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $1 200 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> AUD 1 000 000
<class 'str'> $2 000 000
<class 'str'> $2 000 000
<class 'str'> $93 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan

<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> €9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 4 300 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> £275 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $950 000
<class 'float'> nan
<class 'str'> $686 033
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $2 100 000
<class 'str'> $3 000 000
<class 'str'> $3 000 000
<class 'str'> $1 800 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 5 500 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $1 400 000
<class 'float'> nan
<class 'str'> $650 000
<class 'str'> $300 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> CAD 2 300 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000
<class 'str'> $1 200 000
<class 'str'> $75 000
<class 'str'> $250 000
<class 'str'> $6 400 000
<class 'str'> $1 065 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £300 000
<class 'str'> $806 947
<class 'str'> $175 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 63 000 000
<class 'str'> €2 200 000
<class 'float'> nan
<class 'str'> $125 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $340 000
<class 'str'> $1 750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> IEP 5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $58 000 000
<class 'float'> nan
<class 'str'> FRF 450 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $35 000 000
<class 'str'> $2 750 000
<class 'str'> $3 180 000
<class 'str'> $8 030 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $2 410 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $130 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $3 200 000
<class 'str'> $90 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> INR 32 500 000
<class 'str'> INR 250 000 000
<class 'str'> $1 200 000
<class 'str'> $160 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $94 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $14 000 000
<class 'str'> FRF 6 000 000
<class 'str'> FRF 4 700 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $1 000 000
<class 'str'> £6 000 000
<class 'str'> $25 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRR 22 000 000
<class 'str'> $25 000 000
<class 'str'> €5 500 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $12 000 000
<class 'str'> $250 000
<class 'str'> $62 000
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 479 000
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $40 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $1 752 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $17 000 000
<class 'str'> €1 000 000
<class 'str'> $46 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $42 000 000
<class 'str'> $29 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $31 500 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $37 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> €19 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $12 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $2 800 000
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $2 883 848
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $29 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $1 000 000
<class 'str'> £30 000
<class 'str'> $7 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $25 000 000
<class 'str'> $70 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $2 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $50 000 000
<class 'str'> $900 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $15 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $935 000
<class 'str'> $10 000 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $2 000 000
<class 'str'> $39 000 000
<class 'str'> $63 600 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $83 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $63 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 100 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $250 000
<class 'str'> CAD 1 500 000
<class 'str'> $4 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $34 000 000
<class 'str'> $60 000 000
<class 'str'> $23 000 000
<class 'str'> $2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 530 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> DEM 6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $927 262
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'str'> $6 000 000
<class 'str'> $10 600 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> INR 160 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $25 000 000
<class 'str'> $60 000 000
<class 'str'> DEM 7 000 000
<class 'str'> $190 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $38 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 540 800
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $5 600 000
<class 'str'> ¥1 900 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €14 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> €5 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 769
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 33 000 000
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> $100 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> €4 300 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $1 680 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 39 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> £229 575
<class 'str'> $58 000 000
<class 'str'> $10 000 000
<class 'str'> $2 000 000
<class 'str'> $10 000 000
<class 'str'> CAD 6 000 000
<class 'float'> nan
<class 'str'> CAD 8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 600 000
<class 'str'> $165 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 95 000 000
<class 'str'> FRF 60 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 328 737
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> FRF 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $20 000 000
<class 'str'> $5 500 000
<class 'str'> $3 500 000
<class 'str'> $2 000 000
<class 'str'> $5 000 000
<class 'str'> AUD 8 240 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $9 000 000
<class 'str'> $54 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $10 000 000
<class 'str'> $2 777 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $40 000 000
<class 'str'> $53 000 000
<class 'str'> $57 000 000
<class 'str'> $485 000
<class 'str'> $1 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $250 000
<class 'str'> $12 000 000
<class 'str'> $26 000 000
<class 'str'> $35 000 000
<class 'str'> $425 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $20 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> FRF 40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £500 000
<class 'str'> $32 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $120 000
<class 'str'> $120 000
<class 'str'> $180 000
<class 'str'> $64 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $160 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 100 000
<class 'float'> nan
<class 'str'> $829 000
<class 'str'> $35 000 000
<class 'str'> $19 000 000
<class 'str'> FRF 116 000 000
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> £160 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> £100 000
<class 'str'> $1 900 000
<class 'str'> $500 000
<class 'str'> $2 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €5 000 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $250 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 1 400 000
<class 'str'> $8 000 000
<class 'str'> $3 500 000
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> FRF 5 500 500
<class 'str'> $40 000
<class 'str'> $1 140 000
<class 'str'> $29 000 000
<class 'str'> FRF 115 000 000
<class 'str'> $100 000 000
<class 'str'> $92 000 000
<class 'str'> $185 000 000
<class 'str'> $150 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $3 700 000
<class 'float'> nan
<class 'str'> $76 000
<class 'str'> $12 000 000
<class 'str'> $4 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $235 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $2 200 000
<class 'str'> $3 600 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $3 500 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $3 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 440 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> € 11 000 000
<class 'str'> $22 000 000
<class 'str'> AUD 3 000 000
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $1 500 000
<class 'str'> £2 500 000
<class 'str'> €13 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'float'> nan
<class 'str'> $57 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'str'> €5 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $€1 6,2 00, 000
<class 'float'> nan
<class 'str'> $3 250 000
<class 'str'> $30 000 000
<class 'str'> $3 500 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> € 500 000
<class 'str'> $19 000 000
<class 'str'> FRF 15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 200 000
<class 'str'> $150 000 000
<class 'str'> $2 200 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 800 000
<class 'str'> $500 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $47 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $3 500 000
<class 'str'> $3 000 000
<class 'str'> $750 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> £13 500 000
<class 'str'> $5 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $4 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $8 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'str'> $500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 170 000 000
<class 'float'> nan
<class 'str'> £1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> CAD 3 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> CAD 20 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> INR 200 000 000
<class 'float'> nan
<class 'str'> $110 000 000
<class 'str'> HUF 130 000 000
<class 'str'> $40 000 000
<class 'str'> $115 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $70 000 000
<class 'str'> $30 000 000
<class 'str'> $150 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> CAD 2 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €6 750 000
<class 'str'> $7 000 000
<class 'str'> £1 500
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 800 000
<class 'str'> $2 500 000
<class 'str'> $200 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $40 000 000
<class 'str'> $75 000
<class 'str'> $20 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> € 3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $3 700 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $20 000 000
<class 'str'> $7 500 000
<class 'str'> $4 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $2 900 000
<class 'str'> $81 000 000
<class 'str'> $2 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> €15 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> INR 20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $85 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 19 500 000
<class 'str'> €400 000
<class 'str'> $80 000 000
<class 'str'> €600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 500 000
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $3 700 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> INR 160 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> CAD 1 350 000
<class 'str'> €1 000 000
<class 'str'> €6 700 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> COP 1 650 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $60 000 000
<class 'str'> $4 000 000
<class 'str'> $30 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'str'> $45 000 000
<class 'str'> $175 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 750 000
<class 'str'> $11 500 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $11 500 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $12 000 000
<class 'str'> $6 000 000
<class 'str'> $22 000 000
<class 'str'> $1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $25 000 000
<class 'str'> $3 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> €10 000 000
<class 'str'> $80 000 000
<class 'str'> $8 000 000
<class 'str'> $20 000 000
<class 'str'> $3 600 000
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 3 000 000
<class 'str'> €22 000 000
<class 'str'> $2 000 000
<class 'str'> $18 500 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $910 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> €500 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $52 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $1 000
<class 'str'> £100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €930 679
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> CZK 5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $72 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $49 000 000
<class 'str'> $23 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $170 000 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $11 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $10 800 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $140 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $25 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> AUD 1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 800 000
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $10 000 000
<class 'str'> $100 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $18 000 000
<class 'str'> $3 250 000
<class 'str'> $42 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 200 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $37 000 000
<class 'str'> $130 000 000
<class 'str'> $20 000 000
<class 'str'> £6 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $1 900 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> €6 000 000
<class 'str'> €4 000 000
<class 'str'> NOK 12 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 200 000 000
<class 'str'> $200 000
<class 'str'> $700 000
<class 'str'> $40 000 000
<class 'str'> $13 000 000
<class 'str'> $9 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> AUD 6 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $20 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $160 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 250 000
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $1 500 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $1 000 000
<class 'str'> $20 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $625 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $95 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 100 000
<class 'str'> INR 140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> €5 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $10 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €7 000 000
<class 'str'> €6 850 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> INR 180 000 000
<class 'float'> nan
<class 'str'> $15 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> INR 50 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan

<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $35 000 000
<class 'str'> $22 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> INR 140 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> NOK 890 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $30 000 000
<class 'str'> $8 500 000
<class 'str'> $130 000 000
<class 'str'> $200 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> €1 500 000
<class 'str'> £500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $73 000 000
<class 'str'> $20 000 000
<class 'str'> $18 500 000
<class 'str'> $12 000 000
<class 'str'> $250 000
<class 'str'> $35 000 000
<class 'str'> $3 200 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €10 000 000
<class 'str'> $140 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $2 500 000
<class 'str'> INR 250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $2 900 000
<class 'str'> $9 000 000
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $40 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 750 000 000
<class 'str'> €12 000 000
<class 'str'> $5 000 000
<class 'str'> $48 000 000
<class 'str'> $18 000 000
<class 'str'> €12 000 000
<class 'str'> $12 000 000
<class 'str'> $1 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> HKD 30 000 000
<class 'str'> INR 200 000 000
<class 'str'> €13 000 000
<class 'str'> €10 000 000
<class 'str'> $18 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 405 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 5 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $39 000 000
<class 'str'> $100 000 000
<class 'str'> $12 000 000
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 800 000
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000 000
<class 'str'> $225 000 000
<class 'str'> $6 000 000
<class 'str'> $11 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $185 000 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> €30 000 000
<class 'str'> $25 000 000
<class 'str'> $10 000 000
<class 'str'> $35 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000 000
<class 'str'> $1 500 000
<class 'str'> $60 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 200 000
<class 'str'> €4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'str'> $5 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 600 000 000
<class 'str'> €30 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $7 500 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 500 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 500 000
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 3 400 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> CHF 4 500 000
<class 'str'> $600 000
<class 'str'> $2 500 000
<class 'str'> KRW 100 000
<class 'float'> nan
<class 'str'> 100 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $467
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $602 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $70 000 000
<class 'str'> €7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $80 000 000
<class 'str'> $5 000 000
<class 'str'> $10 000 000
<class 'str'> $1 100 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $3 100 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $570 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 700 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 600 000
<class 'str'> $200 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £612 650
<class 'float'> nan
<class 'str'> $68 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> KRW 3 500 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $430 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 052 780
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'str'> $25 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $29 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> UAH 12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 75 000 000 руб.
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $4 800 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 41 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 4 000 000
<class 'float'> nan
<class 'str'> €668 952
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $10 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> £5 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> €725 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 220 000 000
<class 'str'> $100 000 000
<class 'str'> $8 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> INR 500 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> 2 250 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> €2 500 000
<class 'str'> €9 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 5 500 000
<class 'str'> €13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $5 700 000
<class 'float'> nan

<class 'float'> nan
<class 'str'> $17 000
<class 'str'> $50 000
<class 'str'> €1 100 000
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $17 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> FRF 49 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $5 550
<class 'str'> $1 000 000
<class 'str'> €20 000 000
<class 'str'> $6 000 000
<class 'str'> $34 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 140 000 000 руб.
<class 'str'> $600 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> LVL 780 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> €20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 875 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $6 000 000
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $425 000
<class 'float'> nan
<class 'str'> $3 800 000
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000
<class 'str'> THB 150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €250 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $360 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $115 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 300 000
<class 'str'> £1 200 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $12 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $145 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> UAH 10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 550 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $450 000
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> £700 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> SEK 34 000 000
<class 'float'> nan
<class 'str'> €3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> €1 400 000
<class 'float'> nan
<class 'str'> €3 900 000
<class 'float'> nan
<class 'str'> $450 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> €1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $40 000 000
<class 'str'> $14 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £45
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $475 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 288 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $135 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 6 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $73 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $73 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $23 600 000
<class 'float'> nan
<class 'str'> $7 300 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $2 000 000
<class 'str'> $8 000 000
<class 'str'> $300 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $850 000
<class 'str'> $52 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $12 500 000
<class 'str'> £650 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 850 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 220 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 5 459 115
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $820 000
<class 'str'> €4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 15 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $2 100 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 000 000
<class 'str'> $350 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 150 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $82 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 600 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 1 900 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'str'> $7 600 000
<class 'float'> nan
<class 'float'> nan

<class 'str'> $133 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $68 000 000
<class 'str'> $110 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $82 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NZD 5 950 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $112 000 000
<class 'str'> $69 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £650 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $80 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 600 000
<class 'str'> € 16 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $19 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 400 000
<class 'float'> nan
<class 'str'> DKK 4 700 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 800 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FIM 1 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €170 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $155 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 253 000 000 руб.
<class 'str'> €4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €800 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $325 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $72 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £20 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $120 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £9 000
<class 'str'> $500 000
<class 'str'> $100 000 000
<class 'str'> $35 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000
<class 'float'> nan
<class 'str'> € 5 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> €3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $85 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $6 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 1 000 000 руб.
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 6 000 000 руб.
<class 'str'> $14 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 180 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 073 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 162 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €17 500 000
<class 'str'> $15 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 190 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000
<class 'float'> nan
<class 'str'> $8 500 000
<class 'str'> €1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥2 400 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> €1 000 000
<class 'float'> nan
<class 'str'> $4 638 783
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $850 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $102 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 675 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £25 000
<class 'float'> nan
<class 'str'> $22 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 500 000
<class 'str'> $84 000 000
<class 'float'> nan
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 120 175
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $54 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $29 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $58 000 000
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $36 000 000
<class 'str'> €20 000 000
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $9 200 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 200 000
<class 'str'> €2 800 000
<class 'str'> €2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $51 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 400 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 4 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 622 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 251 794
<class 'str'> INR 140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $58 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $195 000 000
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $795 000
<class 'float'> nan
<class 'str'> 660 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $120 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 162 500 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $79 000 000
<class 'str'> $125 000 000
<class 'str'> $4 400 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $82 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 880 000
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $58 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 255 932
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> $63 000 000
<class 'float'> nan
<class 'str'> $2 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $49 900 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $190 000 000
<class 'float'> nan
<class 'str'> CAD 300 000
<class 'str'> $25 000 000
<class 'str'> $117 000 000
<class 'str'> $7 000 000
<class 'str'> $46 000 000
<class 'str'> $42 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $5 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> €1 948 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 250 000
<class 'str'> $38 000 000
<class 'str'> $225 000 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 977 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> €8 483 818
<class 'str'> $3 500 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 661 530
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> £3 200 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $115 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $68 230
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> CZK 150 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 1 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $13 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $65 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'str'> $225 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $175 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $25 000 000
<class 'str'> $30 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $51 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $40 000 000
<class 'str'> $17 000 000
<class 'str'> €6 500 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'str'> $215 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $17 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> €15 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $170 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> €1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 800 000
<class 'str'> $38 000 000
<class 'str'> $40 000 000
<class 'str'> $160 000 000
<class 'float'> nan
<class 'str'> $58 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $5 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $195 000 000
<class 'str'> $130 000 000
<class 'str'> $68 000 000
<class 'str'> $50 000 000
<class 'str'> $100 000 000
<class 'str'> $12 500 000
<class 'str'> $28 000 000
<class 'str'> $44 500 000
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'str'> $32 000 000
<class 'str'> $8 000 000
<class 'str'> $30 000 000
<class 'str'> $38 000 000
<class 'str'> £20 000 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> €25 000 000
<class 'str'> $28 000 000
<class 'str'> $30 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan

<class 'str'> $130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> €3 238 460
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 300 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $1 000 000
<class 'str'> $1 950 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $2 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 192 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 500 000
<class 'str'> €5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $100 000 000
<class 'str'> €2 000 000
<class 'str'> $30 000 000
<class 'str'> BRL 20 000 000
<class 'str'> $60 000 000
<class 'str'> $28 000 000
<class 'str'> $6 000 000
<class 'str'> $78 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $32 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 200 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> €1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> AUD 2 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $46 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> £385 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $14 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $20 500 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $32 500 000
<class 'str'> $42 000 000
<class 'str'> $60 000 000
<class 'str'> $120 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $2 200 000
<class 'str'> $1 350 000
<class 'str'> $1 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 10 000 000
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $2 500 000
<class 'str'> $20 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> € 18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $400 000
<class 'str'> €6 000 000
<class 'str'> $900 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> SEK 32 000 000
<class 'str'> $28 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> €1 500 000
<class 'float'> nan
<class 'str'> 90 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $52 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $35 000 000
<class 'str'> $120 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $12 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> BYR 5 000 000 000
<class 'str'> €4 800 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'str'> $210 000
<class 'str'> FRF 17 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $1 200 000
<class 'str'> $155 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> THB 18 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $145 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $4 000 000
<class 'str'> €6 000 000
<class 'str'> DEM 19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> CAD 4 500 000
<class 'str'> AUD 10 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> SEK 250 000
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥2 000 000
<class 'str'> $400 000
<class 'str'> $29 000 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $43 000 000
<class 'float'> nan
<class 'str'> DEM 18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $103 000 000
<class 'float'> nan
<class 'str'> DEM 5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 1 000 000 000 руб.
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> AUD 25 000 000
<class 'str'> $75 000 000
<class 'str'> $4 600 000
<class 'str'> $2 500 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £150 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000 000
<class 'str'> $1 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> SEK 14 700 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $73 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> FRF 54 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $2 800 000
<class 'str'> $2 300 000
<class 'str'> $35 000 000
<class 'str'> $37 000 000
<class 'str'> $15 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 300 000
<class 'float'> nan
<class 'str'> €525 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> AUD 5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $6 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $923 000
<class 'str'> €3 850 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $8 495 000
<class 'str'> €3 700 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $2 650 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> HUF 200 000 000
<class 'str'> $22 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> NZD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'str'> $625 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> AUD 80 000
<class 'float'> nan
<class 'str'> £4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $550 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> $170 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $4 000 000
<class 'str'> $13 000 000
<class 'str'> $24 000 000
<class 'str'> $12 000 000
<class 'str'> $32 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> €1 200 000
<class 'str'> $10 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $3 500 000
<class 'str'> FRF 26 000 000
<class 'float'> nan
<class 'str'> £15 000
<class 'str'> $2 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $72 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> CAD 30 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $51 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 150 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 100 000
<class 'str'> $4 000 000
<class 'str'> $180 000 000
<class 'float'> nan
<class 'str'> $2 750 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 500 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> €13 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $120 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $57 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> £8 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'str'> $40 000 000
<class 'str'> $10 000 000
<class 'str'> INR 250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> £2 000 000
<class 'str'> $1 900 000
<class 'str'> $55 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> €8 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> CAD 1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $26 350 000
<class 'str'> $55 000 000
<class 'str'> $29 000 000
<class 'str'> $18 000 000
<class 'str'> $15 000 000
<class 'str'> $30 000 000
<class 'str'> $5 000 000
<class 'str'> $6 000 000
<class 'str'> $2 000 000
<class 'str'> $7 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $140 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $32 000 000
<class 'str'> $150 000
<class 'str'> $3 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 16 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 200 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> €1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $20 000 000
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 740 000
<class 'str'> $25 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 12 600 000
<class 'float'> nan
<class 'str'> SEK 20 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 370 398
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan

<class 'str'> $300 000
<class 'str'> CNY 19 950 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ARS 2 500 000
<class 'str'> CAD 10 000 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> NOK 21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> €15 000 000
<class 'str'> $70 000 000
<class 'str'> $2 300 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $150 000 000
<class 'str'> $37 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $42 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'str'> €6 000 000
<class 'str'> €3 167 000
<class 'str'> $2 000 000
<class 'str'> INR 550 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $3 900 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $180 000
<class 'str'> €7 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €7 000 000
<class 'str'> CZK 55 000 000
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> PLN 3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 4 300 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> INR 420 000 000
<class 'str'> $1 200 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 60 000 000 руб.
<class 'str'> 50 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 9 000 000
<class 'str'> $130 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> €3 500 000
<class 'str'> $16 400 000
<class 'str'> $10 000 000
<class 'str'> BRL 4 000 000
<class 'float'> nan
<class 'str'> €3 200 000
<class 'float'> nan
<class 'str'> INR 130 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FFR 22 500 000
<class 'str'> FRF 21 000 000
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $102 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 3 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 000 000
<class 'str'> PLN 12 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 4 755 000
<class 'str'> SEK 12 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 500 000
<class 'str'> $1 500 000
<class 'str'> $10 000 000
<class 'str'> $30 000 000
<class 'str'> $24 200 000
<class 'str'> $180 000 000
<class 'str'> €8 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> €4 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 250 000
<class 'str'> $125 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $49 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥1 000 000 000
<class 'str'> $65 000 000
<class 'str'> AUD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $62 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $56 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> LTL 1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> VEB 4 273 248
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $84 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $1 600 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 500 000
<class 'float'> nan
<class 'str'> INR 340 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> €1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $26 000 000
<class 'str'> $48 000 000
<class 'str'> INR 102 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> €1 800 000
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $92 000 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> DEM 2 750 000
<class 'float'> nan
<class 'str'> €60 000 000
<class 'str'> $10 000 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $550 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $3 750 000
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $29 000 000
<class 'str'> $10 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $13 000 000
<class 'str'> $58 000 000
<class 'str'> $750 000
<class 'str'> £2 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $750 000
<class 'str'> €1 775 330
<class 'float'> nan
<class 'float'> nan
<class 'str'> $69 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 8 000 000
<class 'float'> nan
<class 'str'> NOK 3 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 4 328 588
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 300 000
<class 'float'> nan
<class 'str'> $2 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 600 000
<class 'str'> DKK 18 400 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> FRF 10 000 000
<class 'float'> nan
<class 'str'> HUF 100 000 000
<class 'str'> $4 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 25 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $9 500 000
<class 'str'> $4 800 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $9 370 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> INR 270 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 000 000
<class 'str'> $320 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $66 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $123 000 000
<class 'float'> nan
<class 'str'> €860 000
<class 'str'> €12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $178 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $33 746 302
<class 'str'> $90 000 000
<class 'str'> $45 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €11 000 000
<class 'str'> AUD 15 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $176 000 000
<class 'float'> nan
<class 'str'> $2 700 000
<class 'str'> $2 100 000
<class 'str'> $3 600 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $215 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 3 500 000
<class 'str'> $8 900 000
<class 'str'> $50 000 000
<class 'str'> KRW 30 000 000 000
<class 'str'> ZAR 40 000 000
<class 'str'> $30 000 000
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $3 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $16 600 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $12 600 000
<class 'str'> $4 770 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> ESP 350 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> BYR 4 000 000 000
<class 'str'> $16 000 000
<class 'str'> € 17 820 000
<class 'str'> $6 000 000
<class 'str'> $6 400 000
<class 'str'> $1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 600 000
<class 'str'> $12 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $45 000 000
<class 'str'> DEM 15 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> £100 000
<class 'float'> nan
<class 'str'> $95 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $17 000 000
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $200 000
<class 'str'> €6 500 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $60 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $84 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> FRF 7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 50 000
<class 'str'> $7 000 000
<class 'str'> $16 000 000
<class 'str'> $16 000 000
<class 'str'> DEM 5 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 400 000
<class 'str'> $2 000 000
<class 'str'> $25 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> DKK 5 500 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €3 700 000
<class 'float'> nan
<class 'str'> $1 300 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $10 818 775
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €9 150 000
<class 'str'> CAD 1 500 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> AUD 14 000 000
<class 'float'> nan
<class 'str'> $145 000 000
<class 'str'> $11 000 000
<class 'str'> $22 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 18 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $30 000
<class 'str'> £2 200 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $9 300 000
<class 'str'> $4 000 000
<class 'str'> $15 000 000
<class 'str'> $7 500 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> €5 500 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $16 500 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $42 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'str'> € 600 000
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> €8 000 000
<class 'str'> $44 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $2 500 000
<class 'str'> $34 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> €30 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $7 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $22 000 000
<class 'str'> €4 870 000
<class 'str'> $20 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $150 000 000
<class 'str'> €3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 600 000
<class 'str'> $5 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $6 600 000
<class 'str'> €7 880 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $67 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> FRF 75 000 000
<class 'str'> $8 200 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> NOK 1 200 000

<class 'str'> $25 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $2 280 000
<class 'str'> $1 000 000
<class 'str'> PLN 7 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 7 000 000
<class 'str'> AUD 2 500 000
<class 'str'> $70 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 500 000
<class 'str'> $290 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $3 500 000
<class 'str'> $15 000 000
<class 'str'> $33 000
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $1 600 000
<class 'str'> $430 000
<class 'str'> CAD 1 360 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $80 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 123 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'str'> KRW 1 100 000 000
<class 'float'> nan
<class 'str'> €6 500 000
<class 'str'> $100 000
<class 'str'> FFR 30 000 000
<class 'str'> €5 650 000
<class 'float'> nan
<class 'str'> £3 000 000
<class 'str'> $4 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> 30 000 000 руб.
<class 'float'> nan
<class 'str'> €10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $500 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'str'> $35 000 000
<class 'str'> $20 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $190 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $10 000 000
<class 'str'> $3 500 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 000 000
<class 'str'> ITL 16 000 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 1 975 000
<class 'str'> DEM 700 000
<class 'str'> DEM 750 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> FRF 17 000 000
<class 'str'> DKK 18 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 530 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'str'> LTL 3 000 000
<class 'str'> CAD 500 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 100 000 000
<class 'str'> $1 000 000
<class 'str'> $35 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 000 000
<class 'str'> FRF 80 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $3 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $7 500 000
<class 'str'> $3 000 000
<class 'str'> £1 500 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $76 000 000
<class 'str'> $1 499 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 400 000
<class 'str'> $24 000 000
<class 'str'> €1 152 065
<class 'float'> nan
<class 'str'> ¥500 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $8 500 000
<class 'str'> $23 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 20 000 000
<class 'float'> nan
<class 'str'> $226 408
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 6 800 000
<class 'str'> $30 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> KRW 900 000 000
<class 'float'> nan
<class 'str'> €4 400 000
<class 'str'> $46 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> INR 150 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'str'> $12 464
<class 'str'> $40 000 000
<class 'str'> $14 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $30 000 000
<class 'str'> AUD 16 000 000
<class 'str'> $5 000 000
<class 'str'> €30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $28 000 000
<class 'str'> $41 000 000
<class 'str'> $4 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000
<class 'str'> $10 000 000
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> €2 472 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $2 000 000
<class 'str'> DKK 16 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> €40 000 000
<class 'str'> CAD 100 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $2 000 000
<class 'str'> $600 000
<class 'str'> $4 200 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 5 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 4 400 000
<class 'str'> DEM 4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $5 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $15 500 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> CAD 5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $113 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €30 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> £50 000
<class 'str'> $6 200 000
<class 'str'> $1 650 000
<class 'str'> ITL 18 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> £320 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'str'> INR 400 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> DKK 8 300 000
<class 'str'> €10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $35 000 000
<class 'str'> $1 100 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> $7 000 000
<class 'str'> CAD 3 200 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $28 000 000
<class 'str'> $4 200 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $5 000 000
<class 'str'> $200 000
<class 'str'> €7 800 000
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $5 000 000
<class 'str'> $5 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'str'> $8 500 000
<class 'float'> nan
<class 'str'> €8 459 177
<class 'str'> $61 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> £7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €11 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 200 000
<class 'str'> $25 000 000
<class 'str'> $1 700 000
<class 'str'> $35 000 000
<class 'str'> $2 500 000
<class 'str'> $1 150 000
<class 'float'> nan
<class 'str'> £7 000 000
<class 'str'> AUD 11 000 000
<class 'str'> $1 000 000
<class 'str'> $39 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €40 000 000
<class 'str'> $100 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 009 653
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> NOK 16 350
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000
<class 'str'> $135 000
<class 'str'> $6 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $74 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $10 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $125 000
<class 'float'> nan
<class 'str'> $1 150 000
<class 'str'> $930 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> INR 700 000 000
<class 'str'> INR 600 000 000
<class 'str'> $5 000 000
<class 'str'> $170 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 600 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $110 000 000
<class 'str'> €18 700 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> £200 000
<class 'str'> $6 000 000
<class 'str'> $500 000
<class 'str'> INR 9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> £300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> €4 574 488
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 19 900 000
<class 'float'> nan
<class 'str'> $160 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $175 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $360 000
<class 'str'> $250 000
<class 'str'> $35 000
<class 'str'> NOK 21 750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $650 000
<class 'str'> €14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $43 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'str'> € 330 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 650 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $190 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'str'> CAD 5 000 000
<class 'float'> nan
<class 'str'> $130 000 000
<class 'str'> $5 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $8 000 000
<class 'str'> £1 200 000
<class 'str'> €5 000 000
<class 'float'> nan
<class 'str'> $1 850 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> CAD 2 000 000
<class 'str'> $9 980 000
<class 'str'> $5 000 000
<class 'str'> $185 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $650 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 400 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> PLN 6 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> €830 000
<class 'str'> £500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $10 000 000
<class 'str'> $82 000 000
<class 'str'> SEK 48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> FRF 50 000 000
<class 'float'> nan
<class 'str'> DEM 600 000
<class 'str'> DEM 450 000
<class 'float'> nan
<class 'str'> DEM 260 000
<class 'str'> DEM 325 000
<class 'str'> DEM 280 000
<class 'str'> DEM 135 000
<class 'str'> DEM 180 000
<class 'str'> DEM 95 000
<class 'str'> $2 700 000
<class 'float'> nan
<class 'str'> KRW 7 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> BRL 9 238 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $42 000 000
<class 'str'> $300 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $210 000
<class 'str'> NOK 17 500 000
<class 'float'> nan
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 40 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €300 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $10 920 000
<class 'str'> €500 000
<class 'float'> nan
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $41 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $3 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $135 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 34 148 170
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> £250 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $84 000 000
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $30 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €13 000 000
<class 'float'> nan
<class 'str'> $175 000
<class 'str'> $8 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 440 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 072 862
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $25 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 7 000 000
<class 'str'> AUD 500 000
<class 'str'> ¥120 000 000
<class 'str'> HKD 200 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $8 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 660 000
<class 'str'> $15 000 000
<class 'str'> $37 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> FIM 12 614 904
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> FIM 5 562 154
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $900 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $6 000 000
<class 'str'> $4 100 000
<class 'str'> £10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $107 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 600 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €17 000 000
<class 'float'> nan
<class 'str'> $6 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 050 000
<class 'str'> £1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €15 000 000
<class 'str'> MYR 2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 500 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $80 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $165 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> €1 000 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'str'> $5 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> INR 850 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 400 000
<class 'str'> €3 200 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $35 000 000
<class 'str'> €10 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $2 500 000
<class 'str'> FRF 14 000 000
<class 'str'> THB 100 000 000
<class 'float'> nan
<class 'str'> $12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $60 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $30 000 000
<class 'str'> $5 000 000
<class 'str'> $4 500 000
<class 'str'> $25 000 000
<class 'str'> $14 000 000
<class 'str'> €5 000 000
<class 'str'> €2 900 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> €12 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'float'> nan
<class 'str'> €5 500 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> €12 000 000
<class 'str'> CLP 153 000 000
<class 'str'> DEM 6 340 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $650 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> €600 000
<class 'str'> $10 500 000
<class 'str'> INR 100 000 000
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $3 200 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> DEM 8 400 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $3 000 000
<class 'str'> $870 000
<class 'str'> CAD 1 900 000
<class 'str'> $15 600 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> € 190 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $105 000 000
<class 'str'> ESP 700 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €100 000
<class 'str'> CAD 2 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $340 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 500 000
<class 'str'> $207 000 000
<class 'str'> $30 000 000
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CZK 70 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 000 000
<class 'str'> CAD 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $49 000 000
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> €1 500 000
<class 'str'> $1 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $10 000 000
<class 'str'> $5 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> €9 600 000
<class 'str'> $4 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $15 500 000
<class 'str'> $4 000 000
<class 'str'> $45 000 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $100 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $160 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 105 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> € 50 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $170 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 184 000 000
<class 'float'> nan
<class 'str'> CAD 1 960 000
<class 'str'> $125 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5
<class 'str'> INR 300 000 000
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $8 000 000
<class 'str'> $6 700 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $26 000 000
<class 'str'> €17 000 000
<class 'str'> $15 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> £4 900 000
<class 'str'> INR 450 000 000
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 000 000
<class 'float'> nan
<class 'str'> £900 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 000 000
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> $270 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 860 000
<class 'float'> nan
<class 'str'> $78 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $190 000 000
<class 'str'> €4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $120 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $5 000 000
<class 'str'> $15 000 000
<class 'str'> $8 500 000
<class 'str'> $25 000 000
<class 'str'> €2 700 000
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $7 000 000
<class 'str'> $200 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $5 000
<class 'str'> $63 000 000
<class 'str'> $15 000 000
<class 'str'> $2 600 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $75 000 000
<class 'str'> $850 000
<class 'float'> nan
<class 'str'> $103 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $12 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 220 000
<class 'str'> $12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'str'> $4 400 000
<class 'float'> nan
<class 'str'> INR 120 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'str'> $40 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $130 000 000
<class 'float'> nan

<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $72 000
<class 'float'> nan
<class 'str'> $6 800 000
<class 'str'> $75 000 000
<class 'str'> $1 500 000
<class 'str'> $50 000 000
<class 'str'> $6 500 000
<class 'str'> $15 000 000
<class 'str'> $54 000 000
<class 'str'> €2 000 000
<class 'float'> nan
<class 'str'> €23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $65 000 000
<class 'str'> $27 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $17 000 000
<class 'str'> $900 000
<class 'str'> $100 000 000
<class 'str'> UAH 16 000 000
<class 'str'> $33 100 000
<class 'str'> $15 000 000
<class 'str'> $14 000 000
<class 'str'> $22 000 000
<class 'str'> $10 000 000
<class 'str'> $53 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $210 000 000
<class 'str'> $4 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $32 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $35 000 000
<class 'str'> CAD 500 000
<class 'str'> TWD 50 000 000
<class 'float'> nan
<class 'str'> CAD 1 200 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $100 000 000
<class 'str'> $80 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'str'> $39 000 000
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $50 000 000
<class 'str'> $4 000 000
<class 'str'> $4 400 000
<class 'float'> nan
<class 'str'> €4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 300 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £7 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $375 000
<class 'str'> $10 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 7 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $53 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> CAD 1 400 000
<class 'str'> $2 500 000
<class 'str'> $90 000
<class 'float'> nan
<class 'str'> FRF 19 000 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 2 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 5 302 677
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $35 000 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $485 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> NOK 28 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $2 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'str'> €1 400 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $75 000 000
<class 'str'> $5 000 000
<class 'str'> $28 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> €2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €15 400 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $105 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €25 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $24 000 000
<class 'str'> $4 000 000
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> ¥5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $6 000 000
<class 'str'> CAD 5 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $57 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'str'> $25 500 000
<class 'str'> $3 000 000
<class 'str'> $6 000 000
<class 'str'> €3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> INR 170 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> INR 40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000
<class 'float'> nan
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> €17 290 000
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $EUR :90 000 00
 (Ев ро)
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> MXN 60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $110 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $1 100 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $31 000 000
<class 'str'> €4 600 000
<class 'str'> $200 000
<class 'str'> €13 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> NOK 8 500 000
<class 'str'> $57 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> €3 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 900 000
<class 'str'> €20 000 000
<class 'float'> nan
<class 'str'> AUD 4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $29 000 000
<class 'str'> CAD 8 500 000
<class 'float'> nan
<class 'str'> NOK 58 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000
<class 'str'> DKK 86 000 000
<class 'str'> $25 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $222 906
<class 'str'> CAD 1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $93 000 000
<class 'str'> $825 000
<class 'str'> $12 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> £1 000 000
<class 'str'> $50 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 300 000 000
<class 'str'> $4 500 000
<class 'str'> CAD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $625 000
<class 'str'> €6 500 000
<class 'str'> KRW 10 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $250 000
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'str'> €8 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥350 000 000
<class 'str'> $13 000 000
<class 'str'> $1 000 000
<class 'str'> $20 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $10 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $25 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €12 000 000
<class 'float'> nan
<class 'str'> $50 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 33 000 000
<class 'str'> $11 000 000
<class 'str'> AUD 5 000 000
<class 'float'> nan
<class 'str'> $835 000
<class 'float'> nan
<class 'str'> PLN 18 820 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $780 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $9 750 000
<class 'str'> $110 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> CAD 10 000 000
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $140 000 000
<class 'str'> €800 000
<class 'str'> $24 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> £3 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $55 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> BEF 1 000 000
<class 'float'> nan
<class 'str'> €500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $12 000 000
<class 'str'> €7 200 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $225 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 20 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £4 000 000
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> €180 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 9 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $7 000 000
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $30 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $175 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 36 500 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $13 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NZD 7 000 000
<class 'str'> $10 000 000
<class 'str'> $6 500 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $175 000 000
<class 'str'> CAD 3 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $36 000 000
<class 'str'> €6 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $30 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 60 000 000
<class 'str'> £300 000
<class 'str'> CAD 6 000 000
<class 'float'> nan
<class 'str'> £2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $12 800 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 100 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $30 000 000
<class 'str'> $10 000 000
<class 'str'> NOK 21 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 17 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $170 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> €1 500 000
<class 'str'> $8 000 000
<class 'str'> $350 000

<class 'str'> €16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 31 300 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $32 000 000
<class 'str'> NOK 6 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> £400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 500 000
<class 'float'> nan
<class 'str'> €7 500 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $5 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> HUF 450 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €40 000 000
<class 'str'> $38 000 000
<class 'str'> 4 000 000 руб.
<class 'float'> nan
<class 'str'> $44 000 000
<class 'str'> $75 000 000
<class 'str'> $55 000 000
<class 'str'> €450 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $3 000 000
<class 'str'> AUD 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $58 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 20 800 000
<class 'str'> $7 500 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 8 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> HUF 20 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $2 000 000
<class 'str'> €5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> €1 600 000
<class 'str'> $16 000 000
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> €16 000 000
<class 'str'> €6 453 637
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> INR 300 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $900 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $115 000 000
<class 'float'> nan
<class 'str'> CAD 2 000 000
<class 'str'> $5 200 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $6 100 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $137 000 000
<class 'str'> $29 000 000
<class 'str'> £7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $43 000 000
<class 'str'> $47 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ITL 500 000 000
<class 'float'> nan
<class 'str'> $350 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $74 000 000
<class 'str'> $3 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $46 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> INR 260 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $75 000
<class 'str'> $70 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 220 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €33 000 000
<class 'str'> $13 000 000
<class 'str'> KRW 5 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $31 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> TWD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> €1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $6 000 000
<class 'str'> $2 600 000
<class 'str'> €9 000 000
<class 'str'> CAD 3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 729 542
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $170 000 000
<class 'str'> €1 500 000
<class 'str'> $7 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> $6 000 000
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $36 000 000
<class 'str'> $13 000 000
<class 'str'> €15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> €8 300 000
<class 'str'> $103 000 000
<class 'float'> nan
<class 'str'> ZAR 20 000 000
<class 'str'> $9 000 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'str'> €9 200 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $12 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $24 500 000
<class 'str'> NOK 38 500 000
<class 'str'> $100 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 284 200
<class 'float'> nan
<class 'str'> CAD 1 800 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000 000
<class 'float'> nan
<class 'str'> $245 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> CNY 150 000 000
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> €5 555 559
<class 'str'> $66 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $3 000
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $877 000
<class 'str'> 60 000 000 руб.
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $325 000
<class 'float'> nan
<class 'str'> $250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 990 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $76 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $5 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 600 000 руб.
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000
<class 'str'> CAD 18 000 000
<class 'str'> $115 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> UAH 15 560 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €13 500 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 900 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $43 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $140 000 000
<class 'str'> $29 000 000
<class 'str'> £6 500 000
<class 'str'> $4 000 000
<class 'str'> $11 000 000
<class 'str'> $1 500 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $19 800 000
<class 'str'> $15 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €17 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> € 1 500 000
<class 'str'> €800
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> INR 300 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> SEK 15 000 000
<class 'str'> $22 000 000
<class 'str'> $7 980 000
<class 'str'> $58 800 000
<class 'str'> €23 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> SEK 15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $2 000 000
<class 'str'> €3 540 000
<class 'float'> nan
<class 'str'> SEK 15 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> CAD 10 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 600 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $15 000 000
<class 'str'> AUD 2 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $87 000 000
<class 'str'> $725 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> PLN 6 000 000
<class 'str'> $3 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> SEK 11 000 000
<class 'str'> $10 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 400 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> €20 000 000
<class 'float'> nan
<class 'str'> DKK 15 500 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 175 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> CNY 4 500 000
<class 'str'> $135 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $27 000 000
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $700 000
<class 'str'> $70 000 000
<class 'str'> $125 000 000
<class 'float'> nan
<class 'str'> SEK 15 000 000
<class 'float'> nan
<class 'str'> $170 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> €1 400 000
<class 'str'> $1 000 000
<class 'str'> DEM 4 000 000
<class 'str'> SEK 15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> AUD 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $3 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> €7 500 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 800 000
<class 'float'> nan
<class 'str'> $61 000 000
<class 'float'> nan
<class 'str'> $145 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> $165 000 000
<class 'str'> $2 700 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> €15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'str'> $74 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $937 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €103 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 115 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €55 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000 000
<class 'str'> $13 000 000
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000

<class 'str'> $8 000 000
<class 'str'> $2 700 000
<class 'str'> $6 000 000
<class 'str'> $46 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $63 000 000
<class 'str'> $28 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'float'> nan
<class 'str'> €5 000 000
<class 'str'> £10 000
<class 'str'> €2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $99 000 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 2 350 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $275 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> €5 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £8 200 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $245 000 000
<class 'float'> nan
<class 'str'> $6 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $1 300 000
<class 'str'> $2 000 000
<class 'str'> $1 250 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $950 000
<class 'str'> $5 500 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> €15 750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $3 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> KRW 250 000 000
<class 'str'> $56 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $5 000 000
<class 'str'> €1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €640 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000
<class 'str'> HUF 120 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €1 605 000
<class 'str'> $2 000 000
<class 'str'> €100 000
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> €3 100 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $777 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $3 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'str'> €8 000 000
<class 'str'> INR 500 000 000
<class 'float'> nan
<class 'str'> $6 200 000
<class 'str'> $13 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $17 500 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $68 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $3 700 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $2 100 000
<class 'str'> GEL 500 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $25 000 000
<class 'str'> €600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 4 500 000 руб.
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 150 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> HKD 200 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> PLN 5 668 688
<class 'str'> $1 200 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 74 000 000 руб.
<class 'str'> $29 000 000
<class 'str'> $2 400 000
<class 'float'> nan
<class 'str'> $2 200 000
<class 'str'> $150 000
<class 'float'> nan
<class 'str'> $3 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $42 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $31 000 000
<class 'str'> $17 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $36 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €250 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 20 100 000
<class 'str'> $30 250 000
<class 'str'> $4 700 000
<class 'str'> 700 000 руб.
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $100 000
<class 'float'> nan
<class 'str'> $2 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> ISK 20 000 000
<class 'str'> $35 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $68 000 000
<class 'float'> nan
<class 'str'> $500
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $29 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DKK 12 600 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $2 700 000
<class 'float'> nan
<class 'str'> $777 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $800 000
<class 'float'> nan
<class 'str'> €525 000
<class 'float'> nan
<class 'str'> $30 000
<class 'float'> nan
<class 'str'> €6 350 000
<class 'str'> $72 000 000
<class 'float'> nan
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> THB 400 000 000
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $10 000
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> €8 770 000
<class 'str'> $7 500 000
<class 'str'> $100 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $70 000 000
<class 'str'> $37 000 000
<class 'str'> $80 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $53 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> NOK 35 304 282
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> $11 000 000
<class 'str'> £1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $10 000 000
<class 'str'> €1 980 000
<class 'str'> $127 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 100 000
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 11 300 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> €10 500 000
<class 'str'> NOK 21 600 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $12 000 000
<class 'str'> $34 000 000
<class 'str'> $80 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> CAD 40 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $68 000 000
<class 'str'> CAD 4 700 000
<class 'float'> nan
<class 'str'> $9 000 000
<class 'str'> SEK 6 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 434 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $1 300 000
<class 'str'> 124 000 000 руб.
<class 'str'> $2 000 000
<class 'str'> $1 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $1 300 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> $3 600 000
<class 'str'> $2 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> 65 000 000 руб.
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $14 000 000
<class 'str'> $3 000 000
<class 'str'> $1 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $900 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> £3 500 000
<class 'str'> $5 000 000
<class 'str'> $11 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 700 000 руб.
<class 'str'> $1 500 000
<class 'str'> $3 500 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> HKD 15 000 000
<class 'str'> $100 000
<class 'str'> THB 65 000 000
<class 'str'> $10 000 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $69 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'str'> $72 000 000
<class 'str'> $30 000
<class 'str'> $8 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $22 000 000
<class 'str'> INR 60 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $24 500 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $43 000
<class 'str'> $2 000 000
<class 'str'> $3 000 000
<class 'str'> $39 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $13 000 000
<class 'str'> £2 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 720 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $81 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> INR 300 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 25 000 000
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $11 000 000
<class 'str'> NOK 55 000
<class 'str'> SEK 2 000 000
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $34 000 000
<class 'str'> $15 000 000
<class 'str'> ISK 200 000 000
<class 'str'> €470 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $57 000 000
<class 'str'> €80 000
<class 'float'> nan
<class 'str'> $1 100 000
<class 'str'> FIM 8 000 000
<class 'str'> $10 000
<class 'str'> €24 000 000
<class 'str'> $190 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> INR 7 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 9 100 000
<class 'str'> $65 000 000
<class 'str'> NOK 35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> 60 000 руб.
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> HUF 700 000 000
<class 'str'> $4 100 000
<class 'str'> CAD 1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 120 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'str'> $16 000 000
<class 'str'> $11 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan

<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 200 000
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> CAD 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> £170 000
<class 'float'> nan
<class 'str'> $22 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> ISK 250 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €7 000 000
<class 'float'> nan
<class 'str'> $400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'str'> $75 000 000
<class 'str'> 51 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> $1 800 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $35 000 000
<class 'str'> $62 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> HKD 80 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $6 000 000
<class 'str'> $56 000 000
<class 'str'> €24 000 000
<class 'str'> $70 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> £75 000
<class 'str'> £2 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $2 900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $150 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $33 000 000
<class 'str'> $30 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $250 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> BRL 12 500 000
<class 'float'> nan
<class 'str'> $3 300 000
<class 'str'> €24 000 000
<class 'float'> nan
<class 'str'> $82 500 000
<class 'str'> $82 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €13 580 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $16 000 000
<class 'str'> $135 000 000
<class 'str'> $2 000 000
<class 'str'> $35 000 000
<class 'str'> $75 000 000
<class 'str'> DEM 2 600 000
<class 'str'> $75 000 000
<class 'str'> $500 000
<class 'str'> $5 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> €8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $30 000 000
<class 'str'> $6 000 000
<class 'str'> $40 000 000
<class 'str'> $43 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $29 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $2 200 000
<class 'float'> nan
<class 'str'> 60 000 000 руб.
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'str'> $125 000 000
<class 'str'> €2 175
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $220 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $225 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ITL 50
<class 'float'> nan
<class 'str'> FRF 6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $220
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $50 000
<class 'str'> $17 500 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $30 000 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> FRF 160 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 500 000
<class 'str'> $30 000
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> €2 200 000
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> $1 000 000
<class 'str'> $15 000 000
<class 'str'> $780 000
<class 'str'> €2 500 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 561 000
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> £700 000
<class 'str'> $110 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 500 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> £4 500
<class 'str'> CNY 100 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'str'> $40 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $1 600 000
<class 'str'> $7 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $3 500 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $14 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $140 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> SGD 4 500 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $68 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'str'> $26 000 000
<class 'str'> $50 000 000
<class 'str'> $40 000 000
<class 'str'> NZD 13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $41 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $23 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> FRF 95 130 000
<class 'str'> $2 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 25 000 000
<class 'float'> nan
<class 'str'> DKK 13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 130 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> €5 000 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 000 000
<class 'str'> CAD 1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> €5 300 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'str'> $94 000 000
<class 'str'> $65 000 000
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 500 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $151 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 500 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 430 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 100 000
<class 'str'> $17 311
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $350 000
<class 'str'> $$1 00, 000
<class 'str'> $13 500 000
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $650 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $2 000
<class 'float'> nan
<class 'str'> $85 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $137 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $53 000
<class 'str'> $5 000 000
<class 'str'> $78 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $4 000 000
<class 'str'> $20 000 000
<class 'str'> €500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $8 000 000
<class 'str'> $2 400 000
<class 'str'> 124 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $78 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $258 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 200 000
<class 'str'> $195 393
<class 'float'> nan
<class 'str'> FRF 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $95 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 800 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 200 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 100 000 000
<class 'float'> nan
<class 'str'> €1 620 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> £1 950 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 37 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $33 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $14 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 29 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 896 000
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $12 800 000
<class 'str'> BRL 2 442 740
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 26 000 000
<class 'float'> nan
<class 'str'> €7 032 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $1 200 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'str'> $35 000 000
<class 'str'> $30 000 000
<class 'str'> AUD 571 000
<class 'float'> nan
<class 'str'> €2 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 300 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> INR 180 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $150 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> €1 900 000
<class 'str'> $2 600 000
<class 'str'> $2 000 000
<class 'str'> €4 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> 3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $48 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $11 500 000
<class 'str'> €6 000 000
<class 'str'> $500 000
<class 'str'> CNY 100 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> NOK 26 000 000
<class 'str'> $14 000 000

<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $95 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> £3 000 000
<class 'str'> $150 000 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $850 000
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $35 000 000
<class 'str'> €4 700 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $19 300 000
<class 'str'> $13 000 000
<class 'str'> $10 000 000
<class 'str'> $15 000 000
<class 'str'> $1 400 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $65 000 000
<class 'float'> nan
<class 'str'> $26 000 000
<class 'str'> $5 000 000
<class 'str'> $2 000 000
<class 'str'> $90 000 000
<class 'str'> $8 300 000
<class 'str'> $51 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $70 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $72 500 000
<class 'str'> $175 000 000
<class 'str'> $34 000 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $6 800 000
<class 'str'> $500 000
<class 'str'> $400 000
<class 'str'> $12 000 000
<class 'str'> $14 000 000
<class 'str'> $63 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $16 000 000
<class 'str'> $15 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $900 000
<class 'str'> $28 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $9 700 000
<class 'str'> $66 000 000
<class 'str'> $800 000
<class 'str'> $2 800 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $500 000
<class 'str'> $72 000 000
<class 'float'> nan
<class 'str'> $27 500 000
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'str'> $28 000 000
<class 'str'> $3 401 376
<class 'float'> nan
<class 'str'> €3 500 000
<class 'str'> $85 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £90 000
<class 'str'> $10 000 000
<class 'str'> CAD 2 200 000
<class 'str'> $116 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> £3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 110 000 000 руб.
<class 'str'> $5 000 000
<class 'str'> $66 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 26 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 7 000 000
<class 'float'> nan
<class 'str'> £2 800 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $50 000 000
<class 'str'> $450 000
<class 'str'> $19 000
<class 'str'> $60 000 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'str'> $13 200 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $55 000 000
<class 'str'> $35 000 000
<class 'str'> $12 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> MXN 37 700 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $1 600 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $68 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $44 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $1 000 000
<class 'str'> $3 000 000
<class 'str'> INR 370 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $163 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $26 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €7 000 000
<class 'float'> nan
<class 'str'> $689 665
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 500 000
<class 'float'> nan
<class 'str'> $370 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 600 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> €5 340 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥1 100 000 000
<class 'str'> $950 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $14 000 000
<class 'str'> $4 000 000
<class 'str'> $60 000 000
<class 'str'> £695 393
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥600 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'str'> $550 000
<class 'str'> €8 400 000
<class 'float'> nan
<class 'str'> $2 900 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> ¥5 000 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥3 000 000
<class 'str'> $4 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> INR 120 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 72 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'str'> $30 000 000
<class 'str'> DEM 25 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $258 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'str'> $140 000
<class 'str'> $150 000
<class 'str'> NZD 350 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $656 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 365 000
<class 'float'> nan
<class 'str'> $519 706
<class 'str'> $46 000 000
<class 'str'> DEM 2 900 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $13 282 712
<class 'str'> $250 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $820 000
<class 'str'> $4 550 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $2 600 000
<class 'float'> nan
<class 'str'> $195 845
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 821 052
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $188 000
<class 'float'> nan
<class 'str'> $1 453 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'str'> $400 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $3 000 000
<class 'str'> $250 000
<class 'str'> $5 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $720 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 202 007
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €500 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $455 000
<class 'str'> $2 300 000
<class 'str'> $1 000 000
<class 'str'> $600 000
<class 'str'> $400 000
<class 'str'> $2 388 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $800 000
<class 'str'> $941 000
<class 'float'> nan
<class 'str'> £100 000
<class 'str'> $500 000
<class 'str'> CAD 1 800 000
<class 'str'> $72 000 000
<class 'str'> $609 000
<class 'float'> nan
<class 'str'> $886 000
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $560 000
<class 'str'> $2 111 250
<class 'str'> $2 169 120
<class 'str'> $439 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $15 000
<class 'str'> $30 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $47 000 000
<class 'str'> $6 000
<class 'str'> AUD 440 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000
<class 'float'> nan
<class 'str'> $180 000
<class 'str'> $397 024
<class 'str'> $65 000 000
<class 'str'> $291 000
<class 'str'> $417 000
<class 'str'> ESP 370 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 24 000 000
<class 'str'> INR 11 200 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $1 900 000
<class 'str'> $750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $114 000
<class 'float'> nan
<class 'str'> €1 850 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 900 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> CNY 10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $149 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> €30 000 000
<class 'float'> nan
<class 'str'> $139 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> 1 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $2 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $1 300 000
<class 'str'> $80 000 000
<class 'str'> £200 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> AUD 650 000
<class 'str'> € 5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 500 000
<class 'float'> nan
<class 'str'> £475 000
<class 'float'> nan
<class 'str'> £450 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 180 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> €30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $1 950 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $115 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'str'> $2 000 000
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $22 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $160 000 000
<class 'str'> $2 000 000
<class 'str'> $2 800 000
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 500 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> €8 555 500
<class 'str'> $20 000 000
<class 'str'> $260 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €10 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> INR 200 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> 220 000 000 руб.
<class 'str'> $2 200 000
<class 'str'> $150 000 000
<class 'str'> 90 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'str'> $15 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $600 000
<class 'str'> AUD 2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €128 800
<class 'str'> $10 000 000
<class 'str'> ¥120 000 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> PLN 24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $60 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> £320 000
<class 'str'> $108 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000
<class 'str'> INR 250 000 000
<class 'str'> $10 205 000
<class 'float'> nan
<class 'str'> 50 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 50 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> $45 000
<class 'float'> nan
<class 'str'> 23 000 000 руб.
<class 'float'> nan
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $26 400 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 80 000 000 руб.
<class 'str'> $3 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $2 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $61 000 000
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> NOK 50 000 000
<class 'float'> nan
<class 'str'> $310 607
<class 'float'> nan
<class 'str'> $1 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 115 000 000 руб.
<class 'str'> $980 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $180 000
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> £135 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $1 800 000
<class 'str'> $325 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $355 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> €1 300 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> €313 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> €3 400 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> £1 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> €6 600 000
<class 'str'> $40 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $4 000 000
<class 'str'> $9 000 000
<class 'str'> $54 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $45 000 000
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $45 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $140 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $200 000
<class 'str'> $1 000 000
<class 'str'> £600 000
<class 'str'> $750 000
<class 'str'> $62 000 000
<class 'str'> $5 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> $75 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $40 000 000
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $7 000 000
<class 'str'> $22 000 000
<class 'str'> €1 000 000
<class 'str'> $3 500 000
<class 'str'> $6 000 000
<class 'str'> $25 000 000
<class 'str'> INR 30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 300 000
<class 'float'> nan
<class 'str'> $9 500 000
<class 'str'> $90 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> 700 000 руб.
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £2 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> CAD 13 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> HUF 280 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'str'> $3 000 000
<class 'str'> $450 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $7 000 000
<class 'str'> $1 000 000
<class 'str'> $68 000 000
<class 'str'> $3 500 000
<class 'str'> $200 000
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> $14 000 000
<class 'str'> $33 000 000
<class 'str'> DKK 10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FRF 100 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $69 000 000
<class 'str'> $1 400 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> $80 000 000
<class 'str'> $30 000 000
<class 'str'> £205 067
<class 'str'> FRF 152 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $37 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $750 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> CAD 2 400 000
<class 'str'> $8 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $6 500 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $11 800 000
<class 'str'> $2 000 000
<class 'str'> €7 000 000
<class 'str'> $21 000 000
<class 'str'> $16 000 000
<class 'str'> $3 000 000
<class 'str'> £3 750 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $110 000 000
<class 'float'> nan
<class 'str'> $75 000 000
<class 'str'> $64 000 000
<class 'str'> $19 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $70 000 000
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> $5 000 000
<class 'str'> $14 000 000
<class 'str'> $6 500 000
<class 'str'> $450 000
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $7 500 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000 000
<class 'str'> £350 000
<class 'str'> $8 000 000
<class 'str'> $700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $10 000 000
<class 'str'> £4 200 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'str'> €6 000 000
<class 'str'> $600 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'str'> $14 000 000
<class 'str'> $70 000 000
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $135 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 45 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $85 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> INR 150 000 000
<class 'str'> $8 500 000
<class 'float'> nan
<class 'str'> $38 000 000
<class 'str'> $80 000 000
<class 'str'> $6 000 000
<class 'str'> $50 000
<class 'str'> $15 000 000
<class 'str'> $11 000 000
<class 'str'> $14 000 000
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $14 000 000
<class 'float'> nan
<class 'str'> €2 000
<class 'str'> $45 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $110 000 000
<class 'str'> $16 000 000
<class 'str'> $150 000 000
<class 'str'> €5 300 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> €1 250 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $22 000 000
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> ¥1 300 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'str'> HKD 35 000 000
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $5 000 000
<class 'str'> $41 300 000
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> £4 300 000
<class 'float'> nan
<class 'str'> $700 000
<class 'str'> £1 000 000
<class 'str'> $115 000 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'str'> $55 000 000
<class 'str'> $12 000 000
<class 'str'> $35 000 000
<class 'str'> $5 952 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $470 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'str'> $75 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> SEK 25 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €5 300 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $110 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'str'> $18 000 000
<class 'str'> $820 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $31 000 000
<class 'float'> nan
<class 'str'> €4 000 000
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> €59 660 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $300 000
<class 'str'> $10 000 000
<class 'str'> $32 000 000
<class 'str'> $15 000 000
<class 'str'> $10 000 000
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $820 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> KRW 10 000 000 000
<class 'float'> nan
<class 'str'> $50 000 000
<class 'str'> $190 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 1 250 000 000
<class 'str'> 120 000 000 руб.
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $19 000 000
<class 'float'> nan
<class 'str'> $150 000 000
<class 'str'> $250 000 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'str'> $22 700 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $787 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $25 000 000
<class 'float'> nan
<class 'str'> $4 450 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $80 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ZAR 5 279 093
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'str'> 100 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $703 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 700 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $9 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'str'> €1 400 000
<class 'str'> $5 300 000
<class 'float'> nan
<class 'str'> $3 200 000
<class 'str'> $169 000
<class 'float'> nan
<class 'str'> 75 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 500 000
<class 'float'> nan
<class 'str'> $65 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $12 880 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 490 375
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> $4 000 000
<class 'str'> $6 000 000
<class 'str'> $3 000 000
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 258 000
<class 'str'> $2 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 590 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> £40 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'str'> £12 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> FIM 5 400 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $990 000
<class 'str'> $1 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> 900 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'str'> THB 200 000 000
<class 'str'> $2 500 000
<class 'str'> CAD 1 200 000
<class 'str'> $180 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $28 000 000
<class 'str'> $500 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> CAD 2 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $24 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $21 000 000
<class 'str'> $16 000 000
<class 'str'> $3 000 000
<class 'str'> $45 000 000
<class 'str'> $400 000
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $11 000 000
<class 'str'> $63 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 000 000
<class 'str'> CAD 7 000 000
<class 'str'> $5 000 000
<class 'str'> $12 000 000
<class 'str'> $8 000 000
<class 'str'> $32 000 000
<class 'float'> nan
<class 'str'> €3 700 000
<class 'str'> €20 000
<class 'float'> nan
<class 'str'> €6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $38 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'str'> CAD 12 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €2 900 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $750 000
<class 'str'> $950 000
<class 'str'> $20 000 000
<class 'str'> $30 000 000
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $12 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $32 000 000
<class 'str'> $17 000 000
<class 'str'> $3 000 000
<class 'str'> $3 400 000
<class 'str'> $3 000 000
<class 'str'> $2 000 000
<class 'str'> $4 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $5 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> NOK 60 000 000
<class 'str'> CAD 700 000
<class 'str'> $24 000 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $700 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> 45 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> ¥90 000 000
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $4 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $8 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $13 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'str'> $3 520 000
<class 'str'> $1 800 000
<class 'str'> $62 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $20 000 000
<class 'float'> nan
<class 'str'> $55 000 000
<class 'str'> $15 000 000
<class 'str'> ESP 420 000 000
<class 'str'> $1 000 000
<class 'float'> nan
<class 'str'> 4 000 000 руб.
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $20 000 000
<class 'str'> $4 000 000
<class 'float'> nan
<class 'str'> $30 000 000
<class 'float'> nan
<class 'str'> $13 000 000
<class 'str'> $2 000 000
<class 'str'> $8 000 000
<class 'str'> $1 000 000
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> INR 6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> €3 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan

<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 300 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $70 000 000
<class 'str'> $11 000 000
<class 'float'> nan
<class 'str'> $75 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $10 000 000
<class 'float'> nan
<class 'str'> $2 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 000 000
<class 'str'> $9 000 000
<class 'float'> nan
<class 'str'> $15 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> £10 000 000
<class 'float'> nan
<class 'str'> $75 000
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 800 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $210 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $17 000 000
<class 'float'> nan
<class 'str'> $1 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $100 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $3 500 000
<class 'str'> CAD 1 340 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $10 000 000
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> FIM 7 400 000
<class 'float'> nan
<class 'str'> $35 000 000
<class 'float'> nan
<class 'str'> $16 000 000
<class 'float'> nan
<class 'str'> $25 000 000
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'str'> $7 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $50 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $18 000 000
<class 'float'> nan
<class 'str'> $22 000 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $7 000 000
<class 'str'> $3 500 000
<class 'str'> $80 000
<class 'str'> $90 000
<class 'str'> $275 000
<class 'str'> $4 200 000
<class 'str'> $80 000 000
<class 'float'> nan
<class 'str'> $27 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 200 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $2 700 000
<class 'float'> nan
<class 'str'> $6 727 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> DEM 8 000 000
<class 'float'> nan
<class 'str'> $2 500 000
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'float'> nan
<class 'str'> $6 000 000
<class 'float'> nan
<class 'float'> nan
<class 'str'> $1 500 000
<class 'float'> nan

In [34]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26559 entries, 0 to 26558
Data columns (total 55 columns):
movie_id             26559 non-null int64
name_rus             26559 non-null object
kp_rating            26558 non-null float64
movie_duration       26559 non-null object
kp_rating_count      26558 non-null float64
movie_year           26559 non-null int64
imdb_rating          25775 non-null float64
imdb_rating_count    25775 non-null float64
countries            26559 non-null object
budget               10348 non-null object
critics_rating       11424 non-null float64
name_eng             22492 non-null object
биография            26559 non-null float64
семейный             26559 non-null float64
мелодрама            26559 non-null float64
история              26559 non-null float64
спорт                26559 non-null float64
документальный       26559 non-null float64
приключения          26559 non-null float64
криминал             26559 non-null float64
вестерн              26559 non-null float64
детектив             26559 non-null float64
фильм-нуар           26559 non-null float64
фэнтези              26559 non-null float64
драма                26559 non-null float64
ужасы                26559 non-null float64
боевик               26559 non-null float64
детский              26559 non-null float64
фантастика           26559 non-null float64
концерт              26559 non-null float64
аниме                26559 non-null float64
музыка               26559 non-null float64
мюзикл               26559 non-null float64
военный              26559 non-null float64
мультфильм           26559 non-null float64
комедия              26559 non-null float64
триллер              26559 non-null float64
для взрослых         26559 non-null float64
Индия                26559 non-null float64
Испания              26559 non-null float64
Россия               26559 non-null float64
Германия             26559 non-null float64
США                  26559 non-null float64
Италия               26559 non-null float64
Канада               26559 non-null float64
СССР                 26559 non-null float64
Корея Южная          26559 non-null float64
Япония               26559 non-null float64
Франция              26559 non-null float64
Великобритания       26559 non-null float64
Азия                 26559 non-null float64
Европа               26559 non-null float64
Африка               26559 non-null float64
Прибалтика           26559 non-null float64
Наше                 26559 non-null float64
dtypes: float64(48), int64(2), object(5)
memory usage: 11.1+ MB

In [6]:
movies.describe()

,Rank,Year,Score,Metascore,Vote,Runtime,Revenue
count,10000.00000,10000.000000,10000.000000,6781.000000,1.000000e+04,10000.000000,7473.000000
mean,5000.50000,1998.116200,6.627530,56.534140,6.448852e+04,108.696900,36.263402
std,2886.89568,18.249608,1.041204,17.965689,1.249423e+05,21.659929,60.882025
min,1.00000,1915.000000,1.300000,10.000000,6.015000e+03,45.000000,0.000000
25%,2500.75000,1991.000000,6.000000,44.000000,1.014725e+04,94.000000,1.890000
50%,5000.50000,2004.000000,6.700000,57.000000,2.117250e+04,105.000000,15.090000
75%,7500.25000,2011.000000,7.400000,70.000000,6.205200e+04,118.000000,43.860000
max,10000.00000,2018.000000,9.600000,99.000000,2.011509e+06,450.000000,936.660000

In [36]:
IMDB_movies = pd.read_csv('IMDb movies.csv')
IMDB_movies.head()

/home/mike/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [39]:
def actor_feature(df):
#     actor_df = df['actors'].fillna('nan')
    actor_name = set([])
    n = 100
    for i in range(n):
        if type(df['actors'].iloc[i]) is str:
            for actor in df['actors'].iloc[i].split(', '):
                actor_name.add(actor)
    
    for actor in actor_name:
        df[str(actor)] = pd.
        for i in range(n):
            if type(df['actors'].iloc[i]) is str:
                if actor in df['actors'].iloc[i]:
                    df[str(actor)].iloc[i] = 1
                else:
                    df[str(actor)].iloc[i] = 0
    return df
df = actor_feature(movies2)
df.head()

KeyError: 'Svend Bille'

In [14]:
movies2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 22 columns):
imdb_title_id            85855 non-null object
title                    85855 non-null object
original_title           85855 non-null object
year                     85855 non-null object
date_published           85855 non-null object
genre                    85855 non-null object
duration                 85855 non-null int64
country                  85791 non-null object
language                 85022 non-null object
director                 85768 non-null object
writer                   84283 non-null object
production_company       81400 non-null object
actors                   85786 non-null object
description              83740 non-null object
avg_vote                 85855 non-null float64
votes                    85855 non-null int64
budget                   23710 non-null object
usa_gross_income         15326 non-null object
worlwide_gross_income    31016 non-null object
metascore                13305 non-null float64
reviews_from_users       78258 non-null float64
reviews_from_critics     74058 non-null float64
dtypes: float64(4), int64(2), object(16)
memory usage: 14.4+ MB

In [15]:
movies2['actors']

0        Blanche Bayliss, William Courtenay, Chauncey D...
1        Elizabeth Tait, John Tait, Norman Campbell, Be...
2        Asta Nielsen, Valdemar Psilander, Gunnar Helse...
3        Helen Gardner, Pearl Sindelar, Miss Fielding, ...
4        Salvatore Papa, Arturo Pirovano, Giuseppe de L...
5        R. Henderson Bland, Percy Dyer, Gene Gauntier,...
6        Pola Negri, Emil Jannings, Harry Liedtke, Edua...
7        Amleto Novelli, Gustavo Serena, Carlo Cattaneo...
8        Aristide Demetriade, Constanta Demetriade, Con...
9        Robert Gemp, Frederick Warde, Albert Gardner, ...
10       Olaf Fønss, Ida Orloff, Ebba Thomsen, Carl Lau...
11       René Navarre, Edmund Breon, Georges Melchior, ...
12       Hilda Borgström, Aron Lindgren, Erik Lindholm,...
13       René Navarre, Edmund Breon, Georges Melchior, ...
14       Lyda Borelli, Mario Bonnard, Gian Paolo Rosmin...
15       Baert, Suzanne Berni, Fernand Crommelynck, Nad...
16       René Navarre, Edmund Breon, Georges Melchior, ...
17       Henry B. Walthall, Josephine Crowell, Lillian ...
18       Paul Wegener, Grete Berger, Lyda Salmonova, Jo...
19       Jane Gail, Ethel Grandin, William H. Turner, M...
20       Fernanda Negri Pouget, Eugenia Tettoni Fior, U...
21       Francesca Bertini, Gustavo Serena, Carlo Benet...
22       Henry B. Walthall, Spottiswoode Aitken, Blanch...
23       William S. Hart, J. Frank Burke, Clara William...
24       Carolina Catena, Lidia Quaranta, Gina Marangon...
25       Mary Pickford, Owen Moore, Isabel Vernon, Geor...
26       Léonce Perret, Louis Leubas, Maurice Lagrenée,...
27       René Navarre, Georges Melchior, Laurent Morléa...
28       Sidney Drew, Edith Storey, Charles Kent, Mrs. ...
29       Paul Wegener, Henrik Galeen, Lyda Salmonova, R...
                               ...
85825    Paz Bascuñán, Regina Blandón, Fernanda Castill...
85826    Saranya Anand, Sreenath Bhasi, Dharmajan Bolga...
85827    Toni Collette, Damian Lewis, Siân Phillips, Jo...
85828    Manesh Krishnan, Gopika Anil, Salim Kumar, Dev...
85829    Dominique Provost-Chalkley, Jessica Clark, Emi...
85830    Faizon Love, Kirk Fox, Tony Todd, Cassie Clare...
85831    Valavane Koumarane, Balasubramanian, Jensan Di...
85832    Riz Ahmed, Aiysha Hart, Kiran Sonia Sawar, Nab...
85833    Sayed Babu, Sunerah Binte Kamal, Josefine Lind...
85834    Master Ajithesh, Anal Akilan, A.R. Bala, Aruvi...
85835    Asyiela Putri Bt Azhar, Mohd Amir Asyraf Bin M...
85836    Hedda Stiernstedt, Rolf Lassgård, Lena Endre, ...
85837    Stephen Lang, William Sadler, Fred Williamson,...
85838    David Thorpe, John Rhys-Davies, Kristyn Getty,...
85839    Ed Helms, Taraji P. Henson, Terrence Little Ga...
85840    Bahram Radan, Mahnaz Afshar, Mehran Ahmadi, Na...
85841    Farhad Aslani, Majid Salehi, Saeed Poursamimi,...
85842    Kan'ichi Kurita, Kiyoshi Kobayashi, Miyuki Saw...
85843    Karthi, Narain, Ramana, George Maryan, Harish ...
85844    Ashima Narwal, Sritha Chandana, Atul Kulkarni,...
85845    Javier Botet, Bruna Cusí, Miki Esparbé, Ivan L...
85846    Ed Westwick, John Hannah, Tom Wisdom, Corey Jo...
85847    Nandu Anand, Roshan Ullas, Manikandan R. Achar...
85848    Lal, Akshara Kishor, Iniya, Narain, Renji Pani...
85849    Vineeth Sreenivasan, Aparna Das, Basil Joseph,...
85850    Dany Boon, Philippe Katerine, Anne Serra, Samu...
85851    Herman Finkers, Johanna ter Steege, Leonie ter...
85852    Anoop Chandran, Indrans, Sona Nair, Simon Brit...
85853    Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...
85854    Maria Morera Colomer, Biel Rossell Pelfort, Is...
Name: actors, Length: 85855, dtype: object

In [4]:
cartoons = pd.read_csv('DisneyMoviesDataset.csv')
cartoons.head()

,Unnamed: 0,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),...,Box office,Story by,Narrated by,Cinematography,Edited by,Screenplay by,Production companies,Adaptation by,Traditional,Simplified
0,0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,...,$418 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,...,$164 million,"['Ted Sears', 'Otto Englander', 'Webb Smith', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,...,$76.4–$83.3 million,"['Joe Grant', 'Dick Huemer']",Deems Taylor,James Wong Howe,NaN,NaN,NaN,NaN,NaN,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,...,"$960,000 (worldwide rentals)",NaN,NaN,Bert Giennon,Paul Weatherwax,NaN,NaN,NaN,NaN,NaN

In [7]:
cartoons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 32 columns):
Unnamed: 0                 432 non-null int64
title                      432 non-null object
Production company         392 non-null object
Release date               431 non-null object
Running time               422 non-null object
Country                    428 non-null object
Language                   430 non-null object
Running time (int)         422 non-null float64
Budget (float)             273 non-null float64
Box office (float)         355 non-null float64
Release date (datetime)    428 non-null object
imdb                       416 non-null float64
metascore                  283 non-null float64
rotten_tomatoes            361 non-null object
Directed by                431 non-null object
Produced by                422 non-null object
Written by                 203 non-null object
Based on                   211 non-null object
Starring                   398 non-null object
Music by                   422 non-null object
Distributed by             429 non-null object
Budget                     276 non-null object
Box office                 359 non-null object
Story by                   139 non-null object
Narrated by                55 non-null object
Cinematography             342 non-null object
Edited by                  395 non-null object
Screenplay by              191 non-null object
Production companies       39 non-null object
Adaptation by              1 non-null object
Traditional                1 non-null object
Simplified                 1 non-null object
dtypes: float64(5), int64(1), object(26)
memory usage: 108.1+ KB

In [8]:
cartoons.describe()

,Unnamed: 0,Running time (int),Budget (float),Box office (float),imdb,metascore
count,432.000000,422.000000,2.730000e+02,3.550000e+02,416.000000,283.000000
mean,215.500000,97.305687,6.358861e+07,1.674014e+08,6.545433,61.487633
std,124.851912,18.959487,7.163732e+07,2.749517e+08,0.960937,16.562658
min,0.000000,40.000000,1.500000e+02,7.700000e+00,1.500000,18.000000
25%,107.750000,86.000000,1.000000e+07,9.850000e+06,6.000000,49.000000
50%,215.500000,96.000000,3.000000e+07,4.290000e+07,6.600000,61.000000
75%,323.250000,106.750000,1.000000e+08,1.865500e+08,7.200000,73.000000
max,431.000000,168.000000,4.106000e+08,1.657000e+09,8.700000,99.000000

# Первоначальная модель kNN

1) Написать алгоритм которая будет сравнивать вектор значений из анкеты с вектором фильма из кинотеки с помощи функции расстояния.

In [40]:
from sklearn.neighbors import NearestNeighbors


neigh = NearestNeighbors(n_neighbors=2, radius=0.4)
neigh.fit(data)
neigh.kneighbors(answer, n, return_distance=False)

# Подготовка Датасета

## Создать признаки

## Удалить пробелы

## Заменить пропущенные

## Категориальный признаки

## Перевести в числовые

## Нормировать

## Объединить

## Скачать измененный

#